VAPOR3: AppSettingsParams Class Reference
AppSettingsParams Class Reference
VAPOR Params Developer API
A class for describing visual features displayed in the visualizer.
#include <AppSettingsParams.h>
Public Member Functions
AppSettingsParams (VAPoR::ParamsBase::StateSave *ssave)
AppSettingsParams (VAPoR::ParamsBase::StateSave *ssave, VAPoR::XmlNode *node)
virtual ~AppSettingsParams ()
const std::string getShortName ()
void restoreDefaults ()
void SetJpegQuality (int val)
long GetJpegQuality () const
void SetAutosaveInterval (int val)
long GetAutosaveInterval () const
bool GetAutosaveEnabled ()
void SetAutosaveEnabled (bool onOff)
bool GetShowWarning () const
void SetShowWarning (bool onOff)
bool GetUseLessAccurate () const
void SetUseLessAccurate (bool onOff)
bool GetTrackMouse () const
void SetTrackMouse (bool onOff)
bool GetShowCitation () const
void SetShowCitation (bool onOff)
void SetMessageSilence (bool val)
bool GetMessageSilence () const
string GetAutosaveName ()
void SetAutosaveName (string name)
string GetLogFileName () const
void SetLogFileName (string name)
bool GetLogfileEnabled () const
void SetLogfileEnabled (bool val)
void SetCurrentJpegQuality (int val)
long GetCurrentJpegQuality () const
void SetCurrentAutosaveInterval (int val)
long GetCurrentAutosaveInterval () const
bool GetCurrentAutosaveEnabled () const
void SetCurrentAutosaveEnabled (bool onOff)
bool GetCurrentShowWarning () const
void SetCurrentShowWarning (bool onOff)
bool GetCurrentUseLessAccurate () const
void SetCurrentUseLessAccurate (bool onOff)
bool GetCurrentTrackMouse () const
void SetCurrentTrackMouse (bool onOff)
bool GetCurrentShowCitation () const
void SetCurrentShowCitation (bool onOff)
string GetCurrentAutosaveName () const
void SetCurrentAutosaveName (string name)
string GetCurrentLogFileName () const
void SetCurrentLogFileName (string name)
void SetCurrentMessageSilence (bool val)
bool GetCurrentMessageSilence () const
bool GetCurrentLogfileEnabled () const
void SetCurrentLogfileEnabled (bool val)
Public Member Functions inherited from VAPoR::ParamsBase
ParamsBase (StateSave *ssave, const string &classname)
ParamsBase (StateSave *ssave, XmlNode *node)
ParamsBase (const ParamsBase &rhs)
Copy constructor.
ParamsBase & operator= (const ParamsBase &rhs)
ParamsBase (ParamsBase &&)=delete
ParamsBase & operator= (ParamsBase &)=delete
bool operator== (const ParamsBase &rhs) const
Equivalence operator.
bool operator!= (const ParamsBase &rhs) const
virtual ~ParamsBase ()
void SetParent (ParamsBase *parent)
XmlNode * GetNode () const
void BeginGroup (const string &description)
void EndGroup ()
void IntermediateChange ()
virtual vector< long > GetValueLongVec (const string tag) const
virtual vector< long > GetValueLongVec (const string tag, const vector< long > &defaultVal) const
virtual long GetValueLong (const string tag, long defaultVal) const
virtual vector< double > GetValueDoubleVec (const string tag) const
virtual vector< double > GetValueDoubleVec (const string tag, const vector< double > &defaultVal) const
virtual double GetValueDouble (const string tag, double defaultVal) const
virtual vector< string > GetValueStringVec (const string tag) const
virtual vector< string > GetValueStringVec (const string tag, const vector< string > &defaultVal) const
virtual string GetValueString (const string tag, string defaultVal) const
virtual void SetValueLongVec (const string &tag, string description, const vector< long > &values)
virtual void SetValueLong (const string &tag, string description, long value)
virtual void SetValueDoubleVec (const string &tag, string description, const vector< double > &values)
virtual void SetValueDouble (const string &tag, string description, double value)
virtual void SetValueStringVec (const string &tag, string description, const vector< string > &values)
virtual void SetValueString (const string &tag, string description, const string &value)
string GetName () const
Public Member Functions inherited from Wasp::MyBase
MyBase ()
const string & getClassName () const
Static Public Member Functions
static string GetClassType ()
Static Public Member Functions inherited from Wasp::MyBase
static void SetErrMsg (const char *format,...)
Record a formatted error message.
static void SetErrMsg (int errcode, const char *format,...)
Record a formatted error message and an error code.
static const char * GetErrMsg ()
static void SetErrCode (int err_code)
Record an error code.
static int GetErrCode ()
Retrieve the current error code.
static void SetErrMsgCB (ErrMsgCB_T cb)
static ErrMsgCB_T GetErrMsgCB ()
static void SetErrMsgFilePtr (FILE *fp)
static const FILE * SetErrMsgFilePtr ()
static void SetDiagMsg (const char *format,...)
Record a formatted diagnostic message.
static const char * GetDiagMsg ()
static void SetDiagMsgCB (DiagMsgCB_T cb)
static DiagMsgCB_T GetDiagMsgCB ()
static void SetDiagMsgFilePtr (FILE *fp)
static bool EnableErrMsg (bool enable)
static bool GetEnableErrMsg ()
Additional Inherited Members
Public Types inherited from Wasp::MyBase
typedef void(* ErrMsgCB_T) (const char *msg, int err_code)
typedef void(* DiagMsgCB_T) (const char *msg)
Static Public Attributes inherited from Wasp::MyBase
static char * ErrMsg
static int ErrCode
static int ErrMsgSize
static FILE * ErrMsgFilePtr
static ErrMsgCB_T ErrMsgCB
static char * DiagMsg
static int DiagMsgSize
static FILE * DiagMsgFilePtr
static DiagMsgCB_T DiagMsgCB
static bool Enabled
Protected Member Functions inherited from VAPoR::ParamsBase
ParamsBase (StateSave *ssave)
void Remove (const string &name)
const map< string, string > & GetAttributes ()
void Clear ()
Protected Member Functions inherited from Wasp::MyBase
void SetClassName (const string &name)
Protected Attributes inherited from VAPoR::ParamsBase
StateSave * _ssave
XmlNode * _node
Detailed Description
A class for describing visual features displayed in the visualizer.
The AppSettingsParams class controls various features displayed in the visualizers There is a global AppSettingsParams, that is shared by all windows whose AppSettings is set to "global". There is also a local AppSettingsParams for each window, that users can select whenever there are multiple windows. When local settings are used, they only affect one currently active visualizer. The AppSettingsParams class also has several methods that are useful in setting up data requests from the DataMgr.
Author
Alan Norton
Version
3.0
Date
June 2015
Definition at line 41 of file AppSettingsParams.h.
Constructor & Destructor Documentation
AppSettingsParams() [1/2]
AppSettingsParams::AppSettingsParams (VAPoR::ParamsBase::StateSave * ssave)
AppSettingsParams() [2/2]
AppSettingsParams::AppSettingsParams (VAPoR::ParamsBase::StateSave * ssave, VAPoR::XmlNode * node)
~AppSettingsParams()
virtual AppSettingsParams::~AppSettingsParams () virtual
Member Function Documentation
GetAutosaveEnabled()
bool AppSettingsParams::GetAutosaveEnabled () inline
Definition at line 85 of file AppSettingsParams.h.
References VAPoR::ParamsBase::GetValueLong().
GetAutosaveInterval()
long AppSettingsParams::GetAutosaveInterval () const
Obtain autosave interval
Returns
interval between autosaves
GetAutosaveName()
string AppSettingsParams::GetAutosaveName () inline
Definition at line 106 of file AppSettingsParams.h.
References VAPoR::ParamsBase::GetValueString().
GetClassType()
static string AppSettingsParams::GetClassType () inline static
Definition at line 168 of file AppSettingsParams.h.
GetCurrentAutosaveEnabled()
bool AppSettingsParams::GetCurrentAutosaveEnabled () const inline
Definition at line 132 of file AppSettingsParams.h.
References VAPoR::ParamsBase::GetValueLong().
GetCurrentAutosaveInterval()
long AppSettingsParams::GetCurrentAutosaveInterval () const
Obtain Current autosave interval
Returns
interval between autosaves
GetCurrentAutosaveName()
string AppSettingsParams::GetCurrentAutosaveName () const inline
Definition at line 152 of file AppSettingsParams.h.
References VAPoR::ParamsBase::GetValueString().
GetCurrentJpegQuality()
long AppSettingsParams::GetCurrentJpegQuality () const
GetCurrentLogfileEnabled()
bool AppSettingsParams::GetCurrentLogfileEnabled () const inline
Definition at line 162 of file AppSettingsParams.h.
References VAPoR::ParamsBase::GetValueLong().
GetCurrentLogFileName()
string AppSettingsParams::GetCurrentLogFileName () const inline
Definition at line 156 of file AppSettingsParams.h.
References VAPoR::ParamsBase::GetValueString().
GetCurrentMessageSilence()
bool AppSettingsParams::GetCurrentMessageSilence () const inline
Definition at line 160 of file AppSettingsParams.h.
References VAPoR::ParamsBase::GetValueLong().
GetCurrentShowCitation()
bool AppSettingsParams::GetCurrentShowCitation () const inline
Definition at line 148 of file AppSettingsParams.h.
References VAPoR::ParamsBase::GetValueLong().
GetCurrentShowWarning()
bool AppSettingsParams::GetCurrentShowWarning () const inline
Definition at line 136 of file AppSettingsParams.h.
References VAPoR::ParamsBase::GetValueLong().
GetCurrentTrackMouse()
bool AppSettingsParams::GetCurrentTrackMouse () const inline
Definition at line 144 of file AppSettingsParams.h.
References VAPoR::ParamsBase::GetValueLong().
GetCurrentUseLessAccurate()
bool AppSettingsParams::GetCurrentUseLessAccurate () const inline
Definition at line 140 of file AppSettingsParams.h.
References VAPoR::ParamsBase::GetValueLong().
GetJpegQuality()
long AppSettingsParams::GetJpegQuality () const
Obtain jpeg quality
Returns
jpeg quality level
GetLogfileEnabled()
bool AppSettingsParams::GetLogfileEnabled () const inline
Definition at line 114 of file AppSettingsParams.h.
References VAPoR::ParamsBase::GetValueLong().
GetLogFileName()
string AppSettingsParams::GetLogFileName () const inline
Definition at line 110 of file AppSettingsParams.h.
References VAPoR::ParamsBase::GetValueString().
GetMessageSilence()
bool AppSettingsParams::GetMessageSilence () const inline
Definition at line 105 of file AppSettingsParams.h.
References VAPoR::ParamsBase::GetValueLong().
getShortName()
const std::string AppSettingsParams::getShortName () inline
Pure virtual method on Params. Provide a short name suitable for use in the GUI
Return values
string name
Definition at line 51 of file AppSettingsParams.h.
GetShowCitation()
bool AppSettingsParams::GetShowCitation () const inline
Definition at line 99 of file AppSettingsParams.h.
References VAPoR::ParamsBase::GetValueLong().
GetShowWarning()
bool AppSettingsParams::GetShowWarning () const inline
Definition at line 89 of file AppSettingsParams.h.
References VAPoR::ParamsBase::GetValueLong().
GetTrackMouse()
bool AppSettingsParams::GetTrackMouse () const inline
Definition at line 95 of file AppSettingsParams.h.
References VAPoR::ParamsBase::GetValueLong().
GetUseLessAccurate()
bool AppSettingsParams::GetUseLessAccurate () const inline
Definition at line 92 of file AppSettingsParams.h.
References VAPoR::ParamsBase::GetValueLong().
restoreDefaults()
void AppSettingsParams::restoreDefaults ()
Restore default settings performed on user request.
SetAutosaveEnabled()
void AppSettingsParams::SetAutosaveEnabled (bool onOff) inline
Definition at line 87 of file AppSettingsParams.h.
References VAPoR::ParamsBase::SetValueLong().
SetAutosaveInterval()
void AppSettingsParams::SetAutosaveInterval (int val)
Specify autosave interval
Parameters
[in] val autosave interval >= 1
SetAutosaveName()
void AppSettingsParams::SetAutosaveName (string name) inline
Definition at line 108 of file AppSettingsParams.h.
References VAPoR::ParamsBase::SetValueString().
SetCurrentAutosaveEnabled()
void AppSettingsParams::SetCurrentAutosaveEnabled (bool onOff) inline
Definition at line 134 of file AppSettingsParams.h.
References VAPoR::ParamsBase::SetValueLong().
SetCurrentAutosaveInterval()
void AppSettingsParams::SetCurrentAutosaveInterval (int val)
Specify current autosave interval
Parameters
[in] val autosave interval >= 1
SetCurrentAutosaveName()
void AppSettingsParams::SetCurrentAutosaveName (string name) inline
Definition at line 154 of file AppSettingsParams.h.
References VAPoR::ParamsBase::SetValueString().
SetCurrentJpegQuality()
void AppSettingsParams::SetCurrentJpegQuality (int val)
Specify current jpeg quality level
Parameters
[in] val quality level (1-99)
SetCurrentLogfileEnabled()
void AppSettingsParams::SetCurrentLogfileEnabled (bool val) inline
Definition at line 164 of file AppSettingsParams.h.
References VAPoR::ParamsBase::SetValueLong().
SetCurrentLogFileName()
void AppSettingsParams::SetCurrentLogFileName (string name) inline
Definition at line 157 of file AppSettingsParams.h.
References VAPoR::ParamsBase::SetValueString().
SetCurrentMessageSilence()
void AppSettingsParams::SetCurrentMessageSilence (bool val) inline
Definition at line 158 of file AppSettingsParams.h.
References VAPoR::ParamsBase::SetValueLong().
SetCurrentShowCitation()
void AppSettingsParams::SetCurrentShowCitation (bool onOff) inline
Definition at line 150 of file AppSettingsParams.h.
References VAPoR::ParamsBase::SetValueLong().
SetCurrentShowWarning()
void AppSettingsParams::SetCurrentShowWarning (bool onOff) inline
Definition at line 138 of file AppSettingsParams.h.
References VAPoR::ParamsBase::SetValueLong().
SetCurrentTrackMouse()
void AppSettingsParams::SetCurrentTrackMouse (bool onOff) inline
Definition at line 146 of file AppSettingsParams.h.
References VAPoR::ParamsBase::SetValueLong().
SetCurrentUseLessAccurate()
void AppSettingsParams::SetCurrentUseLessAccurate (bool onOff) inline
Definition at line 142 of file AppSettingsParams.h.
References VAPoR::ParamsBase::SetValueLong().
SetJpegQuality()
void AppSettingsParams::SetJpegQuality (int val)
Specify jpeg quality level
Parameters
[in] val quality level (1-99)
SetLogfileEnabled()
void AppSettingsParams::SetLogfileEnabled (bool val) inline
Definition at line 116 of file AppSettingsParams.h.
References VAPoR::ParamsBase::SetValueLong().
SetLogFileName()
void AppSettingsParams::SetLogFileName (string name) inline
Definition at line 112 of file AppSettingsParams.h.
References VAPoR::ParamsBase::SetValueString().
SetMessageSilence()
void AppSettingsParams::SetMessageSilence (bool val) inline
Definition at line 103 of file AppSettingsParams.h.
References VAPoR::ParamsBase::SetValueLong().
SetShowCitation()
void AppSettingsParams::SetShowCitation (bool onOff) inline
Definition at line 101 of file AppSettingsParams.h.
References VAPoR::ParamsBase::SetValueLong().
SetShowWarning()
void AppSettingsParams::SetShowWarning (bool onOff) inline
Definition at line 90 of file AppSettingsParams.h.
References VAPoR::ParamsBase::SetValueLong().
SetTrackMouse()
void AppSettingsParams::SetTrackMouse (bool onOff) inline
Definition at line 97 of file AppSettingsParams.h.
References VAPoR::ParamsBase::SetValueLong().
SetUseLessAccurate()
void AppSettingsParams::SetUseLessAccurate (bool onOff) inline
Definition at line 93 of file AppSettingsParams.h.
References VAPoR::ParamsBase::SetValueLong().
The documentation for this class was generated from the following file:
/Users/pearse/VAPOR/apps/vaporgui/AppSettingsParams.h