VAPOR3: BookmarkParams Class Reference
BookmarkParams Class Reference
#include <BookmarkParams.h>
Public Member Functions
BookmarkParams (VAPoR::ParamsBase::StateSave *ssave)
BookmarkParams (VAPoR::ParamsBase::StateSave *ssave, VAPoR::XmlNode *node)
BookmarkParams (const BookmarkParams &rhs)
void SetName (const string &name)
string GetName () const
void SetData (const string &data)
string GetData () const
string GetIconData () const
int GetIconSize () const
size_t GetIconDataSize () const
void SetIcon (int size, const string &data)
Public Member Functions inherited from VAPoR::ParamsBase
ParamsBase (StateSave *ssave, const string &classname)
ParamsBase (StateSave *ssave, XmlNode *node)
ParamsBase (const ParamsBase &rhs)
Copy constructor.
ParamsBase & operator= (const ParamsBase &rhs)
ParamsBase (ParamsBase &&)=delete
ParamsBase & operator= (ParamsBase &)=delete
bool operator== (const ParamsBase &rhs) const
Equivalence operator.
bool operator!= (const ParamsBase &rhs) const
virtual ~ParamsBase ()
void SetParent (ParamsBase *parent)
XmlNode * GetNode () const
void BeginGroup (const string &description)
void EndGroup ()
void IntermediateChange ()
virtual vector< long > GetValueLongVec (const string tag) const
virtual vector< long > GetValueLongVec (const string tag, const vector< long > &defaultVal) const
virtual long GetValueLong (const string tag, long defaultVal) const
virtual vector< double > GetValueDoubleVec (const string tag) const
virtual vector< double > GetValueDoubleVec (const string tag, const vector< double > &defaultVal) const
virtual double GetValueDouble (const string tag, double defaultVal) const
virtual vector< string > GetValueStringVec (const string tag) const
virtual vector< string > GetValueStringVec (const string tag, const vector< string > &defaultVal) const
virtual string GetValueString (const string tag, string defaultVal) const
virtual void SetValueLongVec (const string &tag, string description, const vector< long > &values)
virtual void SetValueLong (const string &tag, string description, long value)
virtual void SetValueDoubleVec (const string &tag, string description, const vector< double > &values)
virtual void SetValueDouble (const string &tag, string description, double value)
virtual void SetValueStringVec (const string &tag, string description, const vector< string > &values)
virtual void SetValueString (const string &tag, string description, const string &value)
string GetName () const
Public Member Functions inherited from Wasp::MyBase
MyBase ()
const string & getClassName () const
Static Public Member Functions
static string GetClassType ()
static int DefaultIconSize ()
Static Public Member Functions inherited from Wasp::MyBase
static void SetErrMsg (const char *format,...)
Record a formatted error message.
static void SetErrMsg (int errcode, const char *format,...)
Record a formatted error message and an error code.
static const char * GetErrMsg ()
static void SetErrCode (int err_code)
Record an error code.
static int GetErrCode ()
Retrieve the current error code.
static void SetErrMsgCB (ErrMsgCB_T cb)
static ErrMsgCB_T GetErrMsgCB ()
static void SetErrMsgFilePtr (FILE *fp)
static const FILE * SetErrMsgFilePtr ()
static void SetDiagMsg (const char *format,...)
Record a formatted diagnostic message.
static const char * GetDiagMsg ()
static void SetDiagMsgCB (DiagMsgCB_T cb)
static DiagMsgCB_T GetDiagMsgCB ()
static void SetDiagMsgFilePtr (FILE *fp)
static bool EnableErrMsg (bool enable)
static bool GetEnableErrMsg ()
Static Public Attributes
static const string NameTag
static const string DataTag
static const string IconDataTag
static const string IconSizeTag
Static Public Attributes inherited from Wasp::MyBase
static char * ErrMsg
static int ErrCode
static int ErrMsgSize
static FILE * ErrMsgFilePtr
static ErrMsgCB_T ErrMsgCB
static char * DiagMsg
static int DiagMsgSize
static FILE * DiagMsgFilePtr
static DiagMsgCB_T DiagMsgCB
static bool Enabled
Additional Inherited Members
Public Types inherited from Wasp::MyBase
typedef void(* ErrMsgCB_T) (const char *msg, int err_code)
typedef void(* DiagMsgCB_T) (const char *msg)
Protected Member Functions inherited from VAPoR::ParamsBase
ParamsBase (StateSave *ssave)
void Remove (const string &name)
const map< string, string > & GetAttributes ()
void Clear ()
Protected Member Functions inherited from Wasp::MyBase
void SetClassName (const string &name)
Protected Attributes inherited from VAPoR::ParamsBase
StateSave * _ssave
XmlNode * _node
Detailed Description
Definition at line 21 of file BookmarkParams.h.
Constructor & Destructor Documentation
BookmarkParams() [1/3]
BookmarkParams::BookmarkParams (VAPoR::ParamsBase::StateSave * ssave)
BookmarkParams() [2/3]
BookmarkParams::BookmarkParams (VAPoR::ParamsBase::StateSave * ssave, VAPoR::XmlNode * node)
BookmarkParams() [3/3]
BookmarkParams::BookmarkParams (const BookmarkParams & rhs)
Member Function Documentation
DefaultIconSize()
static int BookmarkParams::DefaultIconSize () inline static
Definition at line 55 of file BookmarkParams.h.
GetClassType()
static string BookmarkParams::GetClassType () inline static
Definition at line 27 of file BookmarkParams.h.
GetData()
string BookmarkParams::GetData () const inline
Definition at line 38 of file BookmarkParams.h.
References VAPoR::ParamsBase::GetValueString().
GetIconData()
string BookmarkParams::GetIconData () const inline
Definition at line 40 of file BookmarkParams.h.
References VAPoR::ParamsBase::GetValueString().
GetIconDataSize()
size_t BookmarkParams::GetIconDataSize () const inline
Definition at line 43 of file BookmarkParams.h.
GetIconSize()
int BookmarkParams::GetIconSize () const inline
Definition at line 41 of file BookmarkParams.h.
References VAPoR::ParamsBase::GetValueLong().
GetName()
string BookmarkParams::GetName () const inline
Definition at line 35 of file BookmarkParams.h.
References VAPoR::ParamsBase::GetValueString().
SetData()
void BookmarkParams::SetData (const string & data) inline
Definition at line 37 of file BookmarkParams.h.
References VAPoR::ParamsBase::SetValueString().
SetIcon()
void BookmarkParams::SetIcon (int size, const string & data) inline
Definition at line 49 of file BookmarkParams.h.
SetName()
void BookmarkParams::SetName (const string & name) inline
Definition at line 34 of file BookmarkParams.h.
References VAPoR::ParamsBase::SetValueString().
Member Data Documentation
DataTag
const string BookmarkParams::DataTag static
Definition at line 30 of file BookmarkParams.h.
IconDataTag
const string BookmarkParams::IconDataTag static
Definition at line 31 of file BookmarkParams.h.
IconSizeTag
const string BookmarkParams::IconSizeTag static
Definition at line 32 of file BookmarkParams.h.
NameTag
const string BookmarkParams::NameTag static
Definition at line 29 of file BookmarkParams.h.
The documentation for this class was generated from the following file:
/Users/pearse/VAPOR/include/vapor/BookmarkParams.h