VAPOR3: VAPoR::RenderParams Class Reference
VAPoR::RenderParams Class Reference abstract
VAPOR Params Developer API
A Params subclass for managing parameters used by Renderers.
#include <RenderParams.h>
Public Types
enum class SlicePlaneOrientationMode { Rotation = 0 , Normal = 1 }
Public Types inherited from Wasp::MyBase
typedef void(* ErrMsgCB_T) (const char *msg, int err_code)
typedef void(* DiagMsgCB_T) (const char *msg)
Public Member Functions
RenderParams (DataMgr *dataMgr, ParamsBase::StateSave *ssave, const string &classname, int maxdim=3)
RenderParams (DataMgr *dataMgr, ParamsBase::StateSave *ssave, XmlNode *node, int maxdim=3)
RenderParams (const RenderParams &rhs)
RenderParams & operator= (const RenderParams &rhs)
virtual ~RenderParams ()
virtual int Initialize ()
int ResetUserExtentsToDataExents (string var="")
virtual bool IsEnabled () const
virtual void SetEnabled (bool val)
virtual void SetVariableName (string varName)
string GetVariableName () const
virtual void SetAuxVariableNames (vector< string > varName)
vector< string > GetAuxVariableNames () const
bool UseAuxVariable () const
string GetFirstVariableName () const
virtual void SetFieldVariableNames (vector< string > varNames)
void SetXFieldVariableName (std::string varName)
void SetYFieldVariableName (std::string varName)
void SetZFieldVariableName (std::string varName)
vector< string > GetFieldVariableNames () const
std::string GetXFieldVariableName () const
std::string GetYFieldVariableName () const
std::string GetZFieldVariableName () const
vector< string > GetDistribVariableNames () const
virtual void SetRefinementLevel (int numrefinements)
virtual int GetRefinementLevel () const
virtual int GetCompressionLevel () const
virtual void SetCompressionLevel (int val)
void SetHistoStretch (float factor)
float GetHistoStretch () const
virtual ColorbarPbase * GetColorbarPbase () const
Obtain ColorbarPBase (used to specify Color Bar properties) from RenderParams.
virtual void SetColorbarPbase (ColorbarPbase *pb)
virtual MapperFunction * GetMapperFunc (string varname)
virtual void RemoveMapperFunc (string varname)
Remove the mapper function for the named variable.
virtual void SetMapperFunc (string varname, MapperFunction *tf)
virtual Box * GetBox () const
void SetCursorCoords (const float coords[2])
void GetCursorCoords (float coords[2]) const
virtual void SetHeightVariableName (string varname)
virtual string GetHeightVariableName () const
bool UseSingleColor () const
virtual void SetColorMapVariableName (string varname)
virtual string GetColorMapVariableName () const
virtual string GetActualColorMapVariableName () const =0
void SetUseSingleColor (bool val)
void SetConstantColor (const float rgb[3])
void SetConstantColor (vector< float > rgb)
void GetConstantColor (float rgb[3]) const
vector< float > GetConstantColor () const
void SetConstantOpacity (float o)
float GetConstantOpacity () const
size_t GetCurrentTimestep () const
void SetCurrentTimestep (size_t ts)
virtual Transform * GetTransform () const
Access the transform used by the renderer.
void initializeBypassFlags ()
virtual void SetDefaultVariables (int dim, bool secondaryColormapVariable)
virtual size_t GetRenderDim () const =0
virtual bool HasIsoValues () const
This should be overriden by params for renderes that support iso values to return true.
virtual vector< double > GetIsoValues (const string &variable)
virtual void SetIsoValues (const string &variable, const vector< double > &values)
vector< double > GetIsoValues ()
void SetIsoValues (const vector< double > &values)
virtual bool GetOrientable () const
Return whether a renderer can be oriented - IE, can this renderer be rotated about an origin point?
vector< double > GetSlicePlaneRotation () const
vector< double > GetSlicePlaneOrigin () const
vector< double > GetSlicePlaneNormal () const
double GetXSlicePlaneOrigin () const
double GetYSlicePlaneOrigin () const
double GetZSlicePlaneOrigin () const
void SetXSlicePlaneOrigin (double xOrigin)
void SetYSlicePlaneOrigin (double yOrigin)
void SetZSlicePlaneOrigin (double zOrigin)
void SetSlicePlaneQuad (const std::vector< CoordType > &quad)
std::vector< CoordType > GetSlicePlaneQuad () const
Public Member Functions inherited from VAPoR::ParamsBase
ParamsBase (StateSave *ssave, const string &classname)
ParamsBase (StateSave *ssave, XmlNode *node)
ParamsBase (const ParamsBase &rhs)
Copy constructor.
ParamsBase & operator= (const ParamsBase &rhs)
ParamsBase (ParamsBase &&)=delete
ParamsBase & operator= (ParamsBase &)=delete
bool operator== (const ParamsBase &rhs) const
Equivalence operator.
bool operator!= (const ParamsBase &rhs) const
virtual ~ParamsBase ()
void SetParent (ParamsBase *parent)
XmlNode * GetNode () const
void BeginGroup (const string &description)
void EndGroup ()
void IntermediateChange ()
virtual vector< long > GetValueLongVec (const string tag) const
virtual vector< long > GetValueLongVec (const string tag, const vector< long > &defaultVal) const
virtual long GetValueLong (const string tag, long defaultVal) const
virtual vector< double > GetValueDoubleVec (const string tag) const
virtual vector< double > GetValueDoubleVec (const string tag, const vector< double > &defaultVal) const
virtual double GetValueDouble (const string tag, double defaultVal) const
virtual vector< string > GetValueStringVec (const string tag) const
virtual vector< string > GetValueStringVec (const string tag, const vector< string > &defaultVal) const
virtual string GetValueString (const string tag, string defaultVal) const
virtual void SetValueLongVec (const string &tag, string description, const vector< long > &values)
virtual void SetValueLong (const string &tag, string description, long value)
virtual void SetValueDoubleVec (const string &tag, string description, const vector< double > &values)
virtual void SetValueDouble (const string &tag, string description, double value)
virtual void SetValueStringVec (const string &tag, string description, const vector< string > &values)
virtual void SetValueString (const string &tag, string description, const string &value)
string GetName () const
Public Member Functions inherited from Wasp::MyBase
MyBase ()
const string & getClassName () const
Static Public Attributes
static const string _variableNameTag
static const string _colorMapVariableNameTag
static const string _heightVariableNameTag
static const string _useSingleColorTag
static const string _constantColorTag
static const string _CompressionLevelTag
static const string _RefinementLevelTag
static const string _xFieldVariableNameTag
static const string _yFieldVariableNameTag
static const string _zFieldVariableNameTag
static const string _constantOpacityTag
static const string CustomHistogramDataTag
static const string CustomHistogramRangeTag
static const string LightingEnabledTag
static const string UserNameTag
static const string XSlicePlaneOriginTag
static const string YSlicePlaneOriginTag
static const string ZSlicePlaneOriginTag
static const string XSlicePlaneRotationTag
static const string YSlicePlaneRotationTag
static const string ZSlicePlaneRotationTag
static const string SampleRateTag
static const string SliceOffsetTag
static const string SlicePlaneNormalXTag
static const string SlicePlaneNormalYTag
static const string SlicePlaneNormalZTag
static const string SlicePlaneOrientationModeTag
Static Public Attributes inherited from Wasp::MyBase
static char * ErrMsg
static int ErrCode
static int ErrMsgSize
static FILE * ErrMsgFilePtr
static ErrMsgCB_T ErrMsgCB
static char * DiagMsg
static int DiagMsgSize
static FILE * DiagMsgFilePtr
static DiagMsgCB_T DiagMsgCB
static bool Enabled
Protected Member Functions
bool InitBoxFromVariable (size_t ts, string varName)
virtual bool GetUseSingleColorDefault () const
Protected Member Functions inherited from VAPoR::ParamsBase
ParamsBase (StateSave *ssave)
void Remove (const string &name)
const map< string, string > & GetAttributes ()
void Clear ()
Protected Member Functions inherited from Wasp::MyBase
void SetClassName (const string &name)
Protected Attributes
DataMgr * _dataMgr
int _maxDim
Protected Attributes inherited from VAPoR::ParamsBase
StateSave * _ssave
XmlNode * _node
Additional Inherited Members
Static Public Member Functions inherited from Wasp::MyBase
static void SetErrMsg (const char *format,...)
Record a formatted error message.
static void SetErrMsg (int errcode, const char *format,...)
Record a formatted error message and an error code.
static const char * GetErrMsg ()
static void SetErrCode (int err_code)
Record an error code.
static int GetErrCode ()
Retrieve the current error code.
static void SetErrMsgCB (ErrMsgCB_T cb)
static ErrMsgCB_T GetErrMsgCB ()
static void SetErrMsgFilePtr (FILE *fp)
static const FILE * SetErrMsgFilePtr ()
static void SetDiagMsg (const char *format,...)
Record a formatted diagnostic message.
static const char * GetDiagMsg ()
static void SetDiagMsgCB (DiagMsgCB_T cb)
static DiagMsgCB_T GetDiagMsgCB ()
static void SetDiagMsgFilePtr (FILE *fp)
static bool EnableErrMsg (bool enable)
static bool GetEnableErrMsg ()
Detailed Description
A Params subclass for managing parameters used by Renderers.
Author
Alan Norton
Version
3.0
Date
February 2014
Definition at line 43 of file RenderParams.h.
Member Enumeration Documentation
SlicePlaneOrientationMode
enum class VAPoR::RenderParams::SlicePlaneOrientationMode strong
Enumerator
Rotation
Normal
Definition at line 597 of file RenderParams.h.
Constructor & Destructor Documentation
RenderParams() [1/3]
VAPoR::RenderParams::RenderParams (DataMgr * dataMgr, ParamsBase::StateSave * ssave, const string & classname, int maxdim = 3)
Standard RenderParams constructor.
Parameters
[in] name std::string name, can be the tag
RenderParams() [2/3]
VAPoR::RenderParams::RenderParams (DataMgr * dataMgr, ParamsBase::StateSave * ssave, XmlNode * node, int maxdim = 3)
RenderParams() [3/3]
VAPoR::RenderParams::RenderParams (const RenderParams & rhs)
~RenderParams()
virtual VAPoR::RenderParams::~RenderParams () virtual
Member Function Documentation
GetActualColorMapVariableName()
virtual string VAPoR::RenderParams::GetActualColorMapVariableName () const pure virtual
Due to legacy code, the "ColorMapVariableName" is not the name of the variable by which the renderer is colormapping, but rather the variable it should use if it is not already using its primary variable or a constant color. This function should return the name of the variable that is currently being used for colormapping.
Implemented in VAPoR::PlotParams, VAPoR::StatisticsParams, VAPoR::BarbParams, VAPoR::ContourParams, VAPoR::FlowParams, VAPoR::HelloParams, VAPoR::ImageParams, VAPoR::ModelParams, VAPoR::ParticleParams, VAPoR::SliceParams, VAPoR::TwoDDataParams, VAPoR::VolumeParams, and VAPoR::WireFrameParams.
GetAuxVariableNames()
vector< string > VAPoR::RenderParams::GetAuxVariableNames () const
Get the auxiliary variable names, e.g. "position along flow"
The default is a vector of length containing the empty string.
Return values
vector<string> variable name
GetBox()
virtual Box * VAPoR::RenderParams::GetBox () const inline virtual
Virtual method to return the Box associated with a Params class. By default returns NULL. All params classes that use a box to define data extents should reimplement this method. Needed to support manipulators.
Return values
Box* returns pointer to the Box associated with this Params.
Definition at line 257 of file RenderParams.h.
GetColorbarPbase()
virtual ColorbarPbase * VAPoR::RenderParams::GetColorbarPbase () const inline virtual
Obtain ColorbarPBase (used to specify Color Bar properties) from RenderParams.
Definition at line 224 of file RenderParams.h.
GetColorMapVariableName()
virtual string VAPoR::RenderParams::GetColorMapVariableName () const virtual
Get the color mapping variable name if any
Return values
string variable name
GetCompressionLevel()
virtual int VAPoR::RenderParams::GetCompressionLevel () const virtual
virtual method indicates current Compression level.
Return values
integer compression level, 0 is most compressed
GetConstantColor() [1/2]
vector< float > VAPoR::RenderParams::GetConstantColor () const inline
Definition at line 326 of file RenderParams.h.
GetConstantColor() [2/2]
void VAPoR::RenderParams::GetConstantColor (float rgb[3]) const
Get the constant color (in r,g,b)
Parameters
[out] rgb A 3-element array use values are in the range 0.0..1.0
See also
SetConstantColor(), GetConstantOpacity(), UseSingleColor()
GetConstantOpacity()
float VAPoR::RenderParams::GetConstantOpacity () const
Get the constant opacity
Return values
opacity
See also
SetConstantColor(), GetConstantOpacity()
GetCurrentTimestep()
size_t VAPoR::RenderParams::GetCurrentTimestep () const inline
Get the current data timestep
Return values
ts current time step
Definition at line 352 of file RenderParams.h.
GetCursorCoords()
void VAPoR::RenderParams::GetCursorCoords (float coords[2]) const
Obtain the 2D cursor coordinates if associated with this RenderParams
Returns
2D cursor coordinates
GetDistribVariableNames()
vector< string > VAPoR::RenderParams::GetDistribVariableNames () const inline
Get the distribution variable names, e.g. used in flow integration.
Return values
vector<string> variable names
Definition at line 185 of file RenderParams.h.
GetFieldVariableNames()
vector< string > VAPoR::RenderParams::GetFieldVariableNames () const
Get the field variable names, e.g. used in flow integration.
Return values
vector<string> variable names. A vector of length 3 containing variable names. The default is 3 empty variable names.
GetFirstVariableName()
string VAPoR::RenderParams::GetFirstVariableName () const
Get the primary variable, or the first valid field variable
Return the first non-empty variable found, first searching the name returned by GetVariableName(), and the ordered list of variables returned by GetFieldVariableNames(). The empty string is returned if no non-empty variable names exist.
Return values
string variable name
GetHeightVariableName()
virtual string VAPoR::RenderParams::GetHeightVariableName () const virtual
Determine variable name being used for terrain height (above or below sea level)
Return values
const string& variable name
GetHistoStretch()
float VAPoR::RenderParams::GetHistoStretch () const
Obtain the stretch factor used in displaying histograms in mapper functions.
Default value is 1.0.
Returns
multiplier that applies to the histogram height.
GetIsoValues() [1/2]
vector< double > VAPoR::RenderParams::GetIsoValues () inline
Definition at line 391 of file RenderParams.h.
References GetIsoValues().
Referenced by GetIsoValues().
GetIsoValues() [2/2]
virtual vector< double > VAPoR::RenderParams::GetIsoValues (const string & variable) inline virtual
Reimplemented in VAPoR::VolumeParams, VAPoR::ContourParams, and VAPoR::VolumeParams.
Definition at line 384 of file RenderParams.h.
References VAssert.
GetMapperFunc()
virtual MapperFunction * VAPoR::RenderParams::GetMapperFunc (string varname) virtual
Obtain current MapperFunction
Get a MapperFunction for the variable varname. If one does not exist it is created.
GetOrientable()
virtual bool VAPoR::RenderParams::GetOrientable () const virtual
Return whether a renderer can be oriented - IE, can this renderer be rotated about an origin point?
Reimplemented in VAPoR::ContourParams, and VAPoR::SliceParams.
GetRefinementLevel()
virtual int VAPoR::RenderParams::GetRefinementLevel () const virtual
Virtual method indicates current number of refinements of this Params.
Return values
integer number of refinements
GetRenderDim()
virtual size_t VAPoR::RenderParams::GetRenderDim () const pure virtual
Return the renderer's current dimension
For renderers that are only capable of operating on variables of a fixed dimensionality (e.g. 2D or 3D) this function will return a constant value: the number of dimensions. For renderers that can operate on a variable of varying dimension this method returns the current dimensionality. The returned value will be between 0 and 3. A value of zero will be returned if the current dimensionality cannot be determined.
Implemented in VAPoR::PlotParams, VAPoR::StatisticsParams, VAPoR::BarbParams, VAPoR::ContourParams, VAPoR::FlowParams, VAPoR::HelloParams, VAPoR::ImageParams, VAPoR::ModelParams, VAPoR::ParticleParams, VAPoR::RayCasterParams, VAPoR::SliceParams, VAPoR::TwoDDataParams, VAPoR::VolumeParams, and VAPoR::WireFrameParams.
GetSlicePlaneNormal()
vector< double > VAPoR::RenderParams::GetSlicePlaneNormal () const
Return the renderer's 3 axis normal for creating ArbitrarilyOrientedRegularGrids.
Return values
vector<double> - Slice's rotation on X, Y, and Z axes, specified in the data's coordinate system Valid values - -1.0 to 1.0 for each axis component
GetSlicePlaneOrigin()
vector< double > VAPoR::RenderParams::GetSlicePlaneOrigin () const
Return the renderer's 3 axis origin for creating ArbitrarilyOrientedRegularGrids.
Return values
vector<double> - Slice's origin on X, Y, and Z axes, specified in the data's coordinate system Valid values - A point within the data domain
GetSlicePlaneQuad()
std::vector< CoordType > VAPoR::RenderParams::GetSlicePlaneQuad () const inline
Return the values for a quad that encloses an arbitrary user-defined plane
Return values
A std::vector<CoordType> of size 4, containing the locations of four vertices.
Definition at line 448 of file RenderParams.h.
GetSlicePlaneRotation()
vector< double > VAPoR::RenderParams::GetSlicePlaneRotation () const
Return the renderer's 3 axis rotation for creating ArbitrarilyOrientedRegularGrids.
Return values
vector<double> - Slice's rotation on X, Y, and Z axes Valid values - -90.0 to 90.0 for each axis component
GetTransform()
virtual Transform * VAPoR::RenderParams::GetTransform () const inline virtual
Access the transform used by the renderer.
Definition at line 361 of file RenderParams.h.
GetUseSingleColorDefault()
virtual bool VAPoR::RenderParams::GetUseSingleColorDefault () const inline protected virtual
Reimplemented in VAPoR::BarbParams, and VAPoR::VolumeIsoParams.
Definition at line 456 of file RenderParams.h.
GetVariableName()
string VAPoR::RenderParams::GetVariableName () const
Get the primary variable name, e.g. used in color mapping or rendering. The default is the empty string, which indicates a no variable.
Return values
string variable name
GetXFieldVariableName()
std::string VAPoR::RenderParams::GetXFieldVariableName () const
Get the X field variable name, e.g. used in flow integration.
Return values
std::string X field variable name.
GetXSlicePlaneOrigin()
double VAPoR::RenderParams::GetXSlicePlaneOrigin () const
Return the renderer's origin value on the X axis for creating ArbitrarilyOrientedRegularGrids.
Return values
double - Slice's origin on the X axis Valid values - A point within the data domain's X axis coordinates
GetYFieldVariableName()
std::string VAPoR::RenderParams::GetYFieldVariableName () const
Get the Y field variable name, e.g. used in flow integration.
Return values
std::string Y field variable name.
GetYSlicePlaneOrigin()
double VAPoR::RenderParams::GetYSlicePlaneOrigin () const
Return the renderer's origin value on the Y axis for creating ArbitrarilyOrientedRegularGrids.
Return values
double - Slice's origin on the Y axis Valid values - A point within the data domain's Y axis coordinates
GetZFieldVariableName()
std::string VAPoR::RenderParams::GetZFieldVariableName () const
Get the Z field variable name, e.g. used in flow integration.
Return values
std::string Z field variable name.
GetZSlicePlaneOrigin()
double VAPoR::RenderParams::GetZSlicePlaneOrigin () const
Return the renderer's origin value on the Z axis for creating ArbitrarilyOrientedRegularGrids.
Return values
double - Slice's origin on the Z axis, specified in the data's coordinate system Valid values - A point within the data domain's Z axis coordinates
HasIsoValues()
virtual bool VAPoR::RenderParams::HasIsoValues () const inline virtual
This should be overriden by params for renderes that support iso values to return true.
Reimplemented in VAPoR::ContourParams, and VAPoR::VolumeIsoParams.
Definition at line 383 of file RenderParams.h.
InitBoxFromVariable()
bool VAPoR::RenderParams::InitBoxFromVariable (size_t ts, string varName) protected
Initialize()
virtual int VAPoR::RenderParams::Initialize () virtual
Initialize the class.
Must be called immediately after the constructor:
RenderParams(DataMgr *, ParamsBase::StateSave *, const string &, int maxdim);
The results of calling any other methods before calling Initialize() are undefined.
Subsequent calls to Initialize() after the first call are a no-op.
Return values
returns integer >= 0 on success, otherwise failure
Reimplemented in VAPoR::FlowParams, VAPoR::ImageParams, and VAPoR::SliceParams.
initializeBypassFlags()
void VAPoR::RenderParams::initializeBypassFlags ()
IsEnabled()
virtual bool VAPoR::RenderParams::IsEnabled () const inline virtual
Determine if this params has been enabled for rendering
Default is false.
Return values
bool true if enabled
Definition at line 80 of file RenderParams.h.
operator=()
RenderParams & VAPoR::RenderParams::operator= (const RenderParams & rhs)
RemoveMapperFunc()
virtual void VAPoR::RenderParams::RemoveMapperFunc (string varname) virtual
Remove the mapper function for the named variable.
ResetUserExtentsToDataExents()
int VAPoR::RenderParams::ResetUserExtentsToDataExents (string var = "")
SetAuxVariableNames()
virtual void VAPoR::RenderParams::SetAuxVariableNames (vector< string > varName) virtual
Specify auxiliary variable name; e.g. "Position along Flow" The default is a vector of length containing the empty string.
Parameters
[in] string varNames. If any element is "0" the element will be quietly set to the empty string, "".
SetColorbarPbase()
virtual void VAPoR::RenderParams::SetColorbarPbase (ColorbarPbase * pb) virtual
Set the ColorbarPbase that specifies properties of the Color bar.
See also
GetColorbarPbase By default the ColorbarPbase is a child of the root node of this RenderParams.
Parameters
[in] pb ColorbarPbase to set.
Returns
0 if successful.
SetColorMapVariableName()
virtual void VAPoR::RenderParams::SetColorMapVariableName (string varname) virtual
Specify the variable being used for color mapping
Parameters
[in] string varName. If any varName is "0" it will be quietly set to the empty string, "".
SetCompressionLevel()
virtual void VAPoR::RenderParams::SetCompressionLevel (int val) virtual
Virtual method sets current Compression level.
Parameters
[in] val compression level, 0 is most compressed
SetConstantColor() [1/2]
void VAPoR::RenderParams::SetConstantColor (const float rgb[3])
Specify a constant color
Specify a constant color is in rgb values between 0 and 1. The constant color is used to color objects when UseSingleColor() returns true.
Parameters
[in] const float rgb[3]
See also
GetConstantColor()
SetConstantColor() [2/2]
void VAPoR::RenderParams::SetConstantColor (vector< float > rgb)
SetConstantOpacity()
void VAPoR::RenderParams::SetConstantOpacity (float o)
Specify a constant opacity. Color is n the between 0 and 1.
Parameters
[in] const float rgb[3]
Return values
0 if successful
SetCurrentTimestep()
void VAPoR::RenderParams::SetCurrentTimestep (size_t ts) inline
Set the current data timestep being used
Parameters
[in] ts current time step
Definition at line 357 of file RenderParams.h.
SetCursorCoords()
void VAPoR::RenderParams::SetCursorCoords (const float coords[2])
Specify the 2D cursor coordinates when associated with this RenderParams
Parameters
[in] coords
SetDefaultVariables()
virtual void VAPoR::RenderParams::SetDefaultVariables (int dim, bool secondaryColormapVariable) virtual
Set reasonable default variables
Parameters
[in] The dimension of the variables being set
[in] Indicates whether we're using color mapped variables
Reimplemented in VAPoR::FlowParams.
SetEnabled()
virtual void VAPoR::RenderParams::SetEnabled (bool val) virtual
Enable or disable this params for rendering
This should be executed between start and end capture which provides the appropriate undo/redo support Accordingly this will not make an entry in the undo/redo queue.
Default is false.
Parameters
[in] bool true to enable, false to disable.
SetFieldVariableNames()
virtual void VAPoR::RenderParams::SetFieldVariableNames (vector< string > varNames) virtual
Specify field variable names; e.g. used in flow integration can be 0 or 3 strings
Parameters
[in] string varNames. If any element is "0" the element will be quietly set to the empty string, "".
SetHeightVariableName()
virtual void VAPoR::RenderParams::SetHeightVariableName (string varname) virtual
Specify the variable being used for height Overrides method on RenderParams
Parameters
[in] string varName. If any varName is "0" it will be quietly set to the empty string, "".
Return values
int 0 if successful;
SetHistoStretch()
void VAPoR::RenderParams::SetHistoStretch (float factor)
Specify a stretch factor used in displaying histograms in mapper functions. Can be ignored if there is no mapper function in the params. Default value is 1.0.
Parameters
[in] factor positive multiplier that applies to the histogram height.
SetIsoValues() [1/2]
virtual void VAPoR::RenderParams::SetIsoValues (const string & variable, const vector< double > & values) inline virtual
Reimplemented in VAPoR::VolumeParams, VAPoR::ContourParams, and VAPoR::VolumeParams.
Definition at line 389 of file RenderParams.h.
References VAssert.
SetIsoValues() [2/2]
void VAPoR::RenderParams::SetIsoValues (const vector< double > & values) inline
Definition at line 392 of file RenderParams.h.
References SetIsoValues().
Referenced by SetIsoValues().
SetMapperFunc()
virtual void VAPoR::RenderParams::SetMapperFunc (string varname, MapperFunction * tf) virtual
Set current MapperFunction
Parameters
[in] varname Name of variable associated with mapping
[in] tf
SetRefinementLevel()
virtual void VAPoR::RenderParams::SetRefinementLevel (int numrefinements) virtual
Virtual method sets current number of refinements of this Params.
Parameters
[in] int refinements
SetSlicePlaneQuad()
void VAPoR::RenderParams::SetSlicePlaneQuad (const std::vector< CoordType > & quad) inline
Set the values for a quad that encloses an arbitrary user-defined plane
Parameters
[in] A std::vector<CoordType> of size 4, containing the locations of four vertices.
Definition at line 444 of file RenderParams.h.
SetUseSingleColor()
void VAPoR::RenderParams::SetUseSingleColor (bool val)
Turn on or off the use of single constant color (versus color map)
Parameters
[in] val true will enable constant color
SetVariableName()
virtual void VAPoR::RenderParams::SetVariableName (string varName) virtual
Specify primary variable name; e.g. used in color mapping or rendering. The default is the empty string, which indicates no variable.
Parameters
[in] string varName. If "0" varName will be quietly set to the empty string, "".
SetXFieldVariableName()
void VAPoR::RenderParams::SetXFieldVariableName (std::string varName)
Set the X field variable name, e.g. used in flow integration.
Parameters
[in] std::string varName for X field
SetXSlicePlaneOrigin()
void VAPoR::RenderParams::SetXSlicePlaneOrigin (double xOrigin)
Set the renderer's origin value on the X axis for creating ArbitrarilyOrientedRegularGrids.
Parameters
[in] double - Value to use for the plane origin on the X axis. Valid values - A point within the data domain's X axis coordinates
SetYFieldVariableName()
void VAPoR::RenderParams::SetYFieldVariableName (std::string varName)
Set the Y field variable name, e.g. used in flow integration.
Parameters
[in] std::string varName for Y field
SetYSlicePlaneOrigin()
void VAPoR::RenderParams::SetYSlicePlaneOrigin (double yOrigin)
Set the renderer's origin value on the Y axis for creating ArbitrarilyOrientedRegularGrids.
Parameters
[in] double - Value to use for the plane origin on the Y axis. Valid values - A point within the data domain's Y axis coordinates
SetZFieldVariableName()
void VAPoR::RenderParams::SetZFieldVariableName (std::string varName)
Set the Z field variable name, e.g. used in flow integration.
Parameters
[in] std::string varName for Z field
SetZSlicePlaneOrigin()
void VAPoR::RenderParams::SetZSlicePlaneOrigin (double zOrigin)
Set the renderer's origin value on the Z axis for creating ArbitrarilyOrientedRegularGrids.
Parameters
[in] double - Value to use for the plane origin on the Z axis. Valid values - A point within the data domain's Z axis coordinates
UseAuxVariable()
bool VAPoR::RenderParams::UseAuxVariable () const inline
Determine if auxiliary variable name is used
Return values
bool true if using auxiliary variable
Definition at line 120 of file RenderParams.h.
UseSingleColor()
bool VAPoR::RenderParams::UseSingleColor () const
Indicate if a single (constant) color is being used
Returns
true if constant single color is used
Member Data Documentation
_colorMapVariableNameTag
const string VAPoR::RenderParams::_colorMapVariableNameTag static
Definition at line 486 of file RenderParams.h.
_CompressionLevelTag
const string VAPoR::RenderParams::_CompressionLevelTag static
Definition at line 490 of file RenderParams.h.
_constantColorTag
const string VAPoR::RenderParams::_constantColorTag static
Definition at line 489 of file RenderParams.h.
_constantOpacityTag
const string VAPoR::RenderParams::_constantOpacityTag static
Definition at line 496 of file RenderParams.h.
_dataMgr
DataMgr* VAPoR::RenderParams::_dataMgr protected
Definition at line 451 of file RenderParams.h.
_heightVariableNameTag
const string VAPoR::RenderParams::_heightVariableNameTag static
Definition at line 487 of file RenderParams.h.
_maxDim
int VAPoR::RenderParams::_maxDim protected
Definition at line 452 of file RenderParams.h.
_RefinementLevelTag
const string VAPoR::RenderParams::_RefinementLevelTag static
Definition at line 491 of file RenderParams.h.
_useSingleColorTag
const string VAPoR::RenderParams::_useSingleColorTag static
Definition at line 488 of file RenderParams.h.
_variableNameTag
const string VAPoR::RenderParams::_variableNameTag static
Definition at line 485 of file RenderParams.h.
_xFieldVariableNameTag
const string VAPoR::RenderParams::_xFieldVariableNameTag static
Definition at line 493 of file RenderParams.h.
_yFieldVariableNameTag
const string VAPoR::RenderParams::_yFieldVariableNameTag static
Definition at line 494 of file RenderParams.h.
_zFieldVariableNameTag
const string VAPoR::RenderParams::_zFieldVariableNameTag static
Definition at line 495 of file RenderParams.h.
CustomHistogramDataTag
const string VAPoR::RenderParams::CustomHistogramDataTag static
Definition at line 497 of file RenderParams.h.
CustomHistogramRangeTag
const string VAPoR::RenderParams::CustomHistogramRangeTag static
Definition at line 498 of file RenderParams.h.
LightingEnabledTag
const string VAPoR::RenderParams::LightingEnabledTag static
Definition at line 499 of file RenderParams.h.
SampleRateTag
const string VAPoR::RenderParams::SampleRateTag static
If a renderer samples data points through a plane (IE - Slice and Contour), this tag identifies the parameter for how many samples to take along that vector.
If a renderer supports rotation about a point of origin (IE - Slice and Contour), this tag identifies the parameter for the origin's location on the X axis.
This tag only applies when 3D data are sliced for contouring or pseudo-coloring slices Applies to data of type: double Valid values: A point within the data domain's X axis coordinates Applies to data of type: long Valid values: 0 to LONG_MAX
Definition at line 556 of file RenderParams.h.
SliceOffsetTag
const string VAPoR::RenderParams::SliceOffsetTag static
If a renderer can be offset from a point of origin (IE - Slice and Contour), this tag identifies the parameter for offsetting the renderer from that point.
If a renderer supports rotation about a point of origin (IE - Slice and Contour), this tag identifies the parameter for the origin's location on the X axis.
This tag only applies when 3D data are sliced for contouring or pseudo-coloring slices Applies to data of type: double Valid values: A point within the data domain's X axis coordinates Applies to data of type: double Valid values: DBL_MIN to DBL_MAX
Definition at line 563 of file RenderParams.h.
SlicePlaneNormalXTag
const string VAPoR::RenderParams::SlicePlaneNormalXTag static
If a renderer can be oriented orthogonally to a normal vector (IE - Slice and Contour), this tag identifies the normal's X component.
If a renderer supports rotation about a point of origin (IE - Slice and Contour), this tag identifies the parameter for the origin's location on the X axis.
This tag only applies when 3D data are sliced for contouring or pseudo-coloring slices Applies to data of type: double Valid values: A point within the data domain's X axis coordinates Applies to data of type: double Typical values: -1.0 to 1.0 Valid values: DBL_MIN to DBL_MAX
Definition at line 571 of file RenderParams.h.
SlicePlaneNormalYTag
const string VAPoR::RenderParams::SlicePlaneNormalYTag static
If a renderer can be oriented orthogonally to a normal vector (IE - Slice and Contour), this tag identifies the normal's Y component.
If a renderer supports rotation about a point of origin (IE - Slice and Contour), this tag identifies the parameter for the origin's location on the X axis.
This tag only applies when 3D data are sliced for contouring or pseudo-coloring slices Applies to data of type: double Valid values: A point within the data domain's X axis coordinates Applies to data of type: double Typical values: -1.0 to 1.0 Valid values: DBL_MIN to DBL_MAX
Definition at line 579 of file RenderParams.h.
SlicePlaneNormalZTag
const string VAPoR::RenderParams::SlicePlaneNormalZTag static
If a renderer can be oriented orthogonally to a normal vector (IE - Slice and Contour), this tag identifies the normal's Z component.
If a renderer supports rotation about a point of origin (IE - Slice and Contour), this tag identifies the parameter for the origin's location on the X axis.
This tag only applies when 3D data are sliced for contouring or pseudo-coloring slices Applies to data of type: double Valid values: A point within the data domain's X axis coordinates Applies to data of type: double Typical values: -1.0 to 1.0 Valid values: DBL_MIN to DBL_MAX
Definition at line 587 of file RenderParams.h.
SlicePlaneOrientationModeTag
const string VAPoR::RenderParams::SlicePlaneOrientationModeTag static
If a renderer can be oriented according to 1) a set of rotationis on the XYZ axes, or 2) according to the orthoganality of a specified normal (IE - Slice and Contour), this tag determines which method is being used to orient the the renderer.
If a renderer supports rotation about a point of origin (IE - Slice and Contour), this tag identifies the parameter for the origin's location on the X axis.
This tag only applies when 3D data are sliced for contouring or pseudo-coloring slices Applies to data of type: double Valid values: A point within the data domain's X axis coordinates Applies to data of type: long Valid values: 0 = SlicePlaneOrientationMode::Rotation, 1 = SlicePlaneOrientationMode::Normal
Definition at line 595 of file RenderParams.h.
UserNameTag
const string VAPoR::RenderParams::UserNameTag static
Definition at line 500 of file RenderParams.h.
XSlicePlaneOriginTag
const string VAPoR::RenderParams::XSlicePlaneOriginTag static
If a renderer supports rotation about a point of origin (IE - Slice and Contour), this tag identifies the parameter for the origin's location on the X axis.
This tag only applies when 3D data are sliced for contouring or pseudo-coloring slices Applies to data of type: double Valid values: A point within the data domain's X axis coordinates
Definition at line 508 of file RenderParams.h.
XSlicePlaneRotationTag
const string VAPoR::RenderParams::XSlicePlaneRotationTag static
If a renderer supports rotation about a point of origin (IE - Slice and Contour), this tag identifies the parameter for the rotation about the X axis.
If a renderer supports rotation about a point of origin (IE - Slice and Contour), this tag identifies the parameter for the origin's location on the X axis.
This tag only applies when 3D data are sliced for contouring or pseudo-coloring slices Applies to data of type: double Valid values: A point within the data domain's X axis coordinates Applies to data of type: double Valid values: -90.0 to 90.0
Definition at line 532 of file RenderParams.h.
YSlicePlaneOriginTag
const string VAPoR::RenderParams::YSlicePlaneOriginTag static
If a renderer supports rotation about a point of origin (IE - Slice and Contour), this tag identifies the parameter for the origin's location on the Y axis.
If a renderer supports rotation about a point of origin (IE - Slice and Contour), this tag identifies the parameter for the origin's location on the X axis.
This tag only applies when 3D data are sliced for contouring or pseudo-coloring slices Applies to data of type: double Valid values: A point within the data domain's X axis coordinates Applies to data of type: double Valid values: A point within the data domain's Y axis coordinates
Definition at line 516 of file RenderParams.h.
YSlicePlaneRotationTag
const string VAPoR::RenderParams::YSlicePlaneRotationTag static
If a renderer supports rotation about a point of origin (IE - Slice and Contour), this tag identifies the parameter for the rotation about the Y axis.
If a renderer supports rotation about a point of origin (IE - Slice and Contour), this tag identifies the parameter for the origin's location on the X axis.
This tag only applies when 3D data are sliced for contouring or pseudo-coloring slices Applies to data of type: double Valid values: A point within the data domain's X axis coordinates Applies to data of type: double Valid values: -90.0 to 90.0
Definition at line 540 of file RenderParams.h.
ZSlicePlaneOriginTag
const string VAPoR::RenderParams::ZSlicePlaneOriginTag static
If a renderer supports rotation about a point of origin (IE - Slice and Contour), this tag identifies the parameter for the origin's location on the Z axis.
If a renderer supports rotation about a point of origin (IE - Slice and Contour), this tag identifies the parameter for the origin's location on the X axis.
This tag only applies when 3D data are sliced for contouring or pseudo-coloring slices Applies to data of type: double Valid values: A point within the data domain's X axis coordinates Applies to data of type: double Valid values: A point within the data domain's Z axis coordinates
Definition at line 524 of file RenderParams.h.
ZSlicePlaneRotationTag
const string VAPoR::RenderParams::ZSlicePlaneRotationTag static
If a renderer supports rotation about a point of origin (IE - Slice and Contour), this tag identifies the parameter for the rotation about the Z axis.
If a renderer supports rotation about a point of origin (IE - Slice and Contour), this tag identifies the parameter for the origin's location on the X axis.
This tag only applies when 3D data are sliced for contouring or pseudo-coloring slices Applies to data of type: double Valid values: A point within the data domain's X axis coordinates Applies to data of type: double Valid values: -90.0 to 90.0
Definition at line 548 of file RenderParams.h.
The documentation for this class was generated from the following file:
/Users/pearse/VAPOR/include/vapor/RenderParams.h