VAPOR3: VAPoR::ColorMap Class Reference
VAPoR::ColorMap Class Reference
#include <ColorMap.h>
Classes
class Color
Public Member Functions
ColorMap (ParamsBase::StateSave *ssave)
Create a ColorMap object from scratch.
ColorMap (ParamsBase::StateSave *ssave, XmlNode *node)
Create a ColorMap object from an existing XmlNode tree.
virtual ~ColorMap ()
void clear ()
TFInterpolator::type GetInterpType () const
void SetInterpType (TFInterpolator::type t)
void SetUseWhitespace (bool enabled)
bool GetUseWhitespace () const
int numControlPoints () const
Color controlPointColor (int index) const
void controlPointColor (int index, Color color)
float controlPointValue (int index) const
float controlPointValueNormalized (int index) const
void controlPointValue (int index, float value)
void controlPointValueNormalized (int index, float value)
void addControlPointAt (float value)
int addNormControlPointAt (float value)
void addControlPointAt (float value, Color color)
int addNormControlPoint (float normValue, Color color)
void deleteControlPoint (int index)
void move (int index, float delta)
Color color (float value) const
Color colorNormalized (float nv) const
Color getDivergingColor (float ratio, float index) const
Color getCorrectiveDivergingColor (float ratio, float index) const
vector< double > GetControlPoints () const
void SetControlPoints (const vector< double > &controlPoints)
void SetDataBounds (const vector< double > &bounds)
vector< double > GetDataBounds () const
float minValue () const
float maxValue () const
void Reverse ()
Public Member Functions inherited from VAPoR::ParamsBase
ParamsBase (StateSave *ssave, const string &classname)
ParamsBase (StateSave *ssave, XmlNode *node)
ParamsBase (const ParamsBase &rhs)
Copy constructor.
ParamsBase & operator= (const ParamsBase &rhs)
ParamsBase (ParamsBase &&)=delete
ParamsBase & operator= (ParamsBase &)=delete
bool operator== (const ParamsBase &rhs) const
Equivalence operator.
bool operator!= (const ParamsBase &rhs) const
virtual ~ParamsBase ()
void SetParent (ParamsBase *parent)
XmlNode * GetNode () const
void BeginGroup (const string &description)
void EndGroup ()
void IntermediateChange ()
virtual vector< long > GetValueLongVec (const string tag) const
virtual vector< long > GetValueLongVec (const string tag, const vector< long > &defaultVal) const
virtual long GetValueLong (const string tag, long defaultVal) const
virtual vector< double > GetValueDoubleVec (const string tag) const
virtual vector< double > GetValueDoubleVec (const string tag, const vector< double > &defaultVal) const
virtual double GetValueDouble (const string tag, double defaultVal) const
virtual vector< string > GetValueStringVec (const string tag) const
virtual vector< string > GetValueStringVec (const string tag, const vector< string > &defaultVal) const
virtual string GetValueString (const string tag, string defaultVal) const
virtual void SetValueLongVec (const string &tag, string description, const vector< long > &values)
virtual void SetValueLong (const string &tag, string description, long value)
virtual void SetValueDoubleVec (const string &tag, string description, const vector< double > &values)
virtual void SetValueDouble (const string &tag, string description, double value)
virtual void SetValueStringVec (const string &tag, string description, const vector< string > &values)
virtual void SetValueString (const string &tag, string description, const string &value)
string GetName () const
Public Member Functions inherited from Wasp::MyBase
MyBase ()
const string & getClassName () const
Static Public Member Functions
static string GetClassType ()
Static Public Member Functions inherited from Wasp::MyBase
static void SetErrMsg (const char *format,...)
Record a formatted error message.
static void SetErrMsg (int errcode, const char *format,...)
Record a formatted error message and an error code.
static const char * GetErrMsg ()
static void SetErrCode (int err_code)
Record an error code.
static int GetErrCode ()
Retrieve the current error code.
static void SetErrMsgCB (ErrMsgCB_T cb)
static ErrMsgCB_T GetErrMsgCB ()
static void SetErrMsgFilePtr (FILE *fp)
static const FILE * SetErrMsgFilePtr ()
static void SetDiagMsg (const char *format,...)
Record a formatted diagnostic message.
static const char * GetDiagMsg ()
static void SetDiagMsgCB (DiagMsgCB_T cb)
static DiagMsgCB_T GetDiagMsgCB ()
static void SetDiagMsgFilePtr (FILE *fp)
static bool EnableErrMsg (bool enable)
static bool GetEnableErrMsg ()
Static Public Attributes
static const string _controlPointsTag
static const string _interpTypeTag
static const string _useWhitespaceTag
static const string _dataBoundsTag
Static Public Attributes inherited from Wasp::MyBase
static char * ErrMsg
static int ErrCode
static int ErrMsgSize
static FILE * ErrMsgFilePtr
static ErrMsgCB_T ErrMsgCB
static char * DiagMsg
static int DiagMsgSize
static FILE * DiagMsgFilePtr
static DiagMsgCB_T DiagMsgCB
static bool Enabled
Additional Inherited Members
Public Types inherited from Wasp::MyBase
typedef void(* ErrMsgCB_T) (const char *msg, int err_code)
typedef void(* DiagMsgCB_T) (const char *msg)
Protected Member Functions inherited from VAPoR::ParamsBase
ParamsBase (StateSave *ssave)
void Remove (const string &name)
const map< string, string > & GetAttributes ()
void Clear ()
Protected Member Functions inherited from Wasp::MyBase
void SetClassName (const string &name)
Protected Attributes inherited from VAPoR::ParamsBase
StateSave * _ssave
XmlNode * _node
Detailed Description
Definition at line 17 of file ColorMap.h.
Constructor & Destructor Documentation
ColorMap() [1/2]
VAPoR::ColorMap::ColorMap (ParamsBase::StateSave * ssave)
Create a ColorMap object from scratch.
ColorMap() [2/2]
VAPoR::ColorMap::ColorMap (ParamsBase::StateSave * ssave, XmlNode * node)
Create a ColorMap object from an existing XmlNode tree.
~ColorMap()
virtual VAPoR::ColorMap::~ColorMap () virtual
Member Function Documentation
addControlPointAt() [1/2]
void VAPoR::ColorMap::addControlPointAt (float value)
addControlPointAt() [2/2]
void VAPoR::ColorMap::addControlPointAt (float value, Color color)
addNormControlPoint()
int VAPoR::ColorMap::addNormControlPoint (float normValue, Color color)
addNormControlPointAt()
int VAPoR::ColorMap::addNormControlPointAt (float value)
clear()
void VAPoR::ColorMap::clear ()
color()
Color VAPoR::ColorMap::color (float value) const
colorNormalized()
Color VAPoR::ColorMap::colorNormalized (float nv) const
controlPointColor() [1/2]
Color VAPoR::ColorMap::controlPointColor (int index) const
controlPointColor() [2/2]
void VAPoR::ColorMap::controlPointColor (int index, Color color)
controlPointValue() [1/2]
float VAPoR::ColorMap::controlPointValue (int index) const
controlPointValue() [2/2]
void VAPoR::ColorMap::controlPointValue (int index, float value)
controlPointValueNormalized() [1/2]
float VAPoR::ColorMap::controlPointValueNormalized (int index) const
controlPointValueNormalized() [2/2]
void VAPoR::ColorMap::controlPointValueNormalized (int index, float value)
deleteControlPoint()
void VAPoR::ColorMap::deleteControlPoint (int index)
GetClassType()
static string VAPoR::ColorMap::GetClassType () inline static
Definition at line 109 of file ColorMap.h.
GetControlPoints()
vector< double > VAPoR::ColorMap::GetControlPoints () const
getCorrectiveDivergingColor()
Color VAPoR::ColorMap::getCorrectiveDivergingColor (float ratio, float index) const
GetDataBounds()
vector< double > VAPoR::ColorMap::GetDataBounds () const
getDivergingColor()
Color VAPoR::ColorMap::getDivergingColor (float ratio, float index) const
GetInterpType()
TFInterpolator::type VAPoR::ColorMap::GetInterpType () const inline
Definition at line 55 of file ColorMap.h.
Referenced by VAPoR::MapperFunction::getColorInterpType().
GetUseWhitespace()
bool VAPoR::ColorMap::GetUseWhitespace () const
Referenced by VAPoR::MapperFunction::getUseWhitespace().
maxValue()
float VAPoR::ColorMap::maxValue () const inline
Definition at line 103 of file ColorMap.h.
minValue()
float VAPoR::ColorMap::minValue () const inline
Definition at line 102 of file ColorMap.h.
move()
void VAPoR::ColorMap::move (int index, float delta)
numControlPoints()
int VAPoR::ColorMap::numControlPoints () const inline
Definition at line 64 of file ColorMap.h.
Reverse()
void VAPoR::ColorMap::Reverse ()
SetControlPoints()
void VAPoR::ColorMap::SetControlPoints (const vector< double > & controlPoints)
SetDataBounds()
void VAPoR::ColorMap::SetDataBounds (const vector< double > & bounds)
The minimum value is stored as normalized coordinates in the parameter space. Therefore, the color map will change relative to any changes in the parameter space. True???
SetInterpType()
void VAPoR::ColorMap::SetInterpType (TFInterpolator::type t)
Referenced by VAPoR::MapperFunction::setColorInterpType().
SetUseWhitespace()
void VAPoR::ColorMap::SetUseWhitespace (bool enabled)
Referenced by VAPoR::MapperFunction::setUseWhitespace().
Member Data Documentation
_controlPointsTag
const string VAPoR::ColorMap::_controlPointsTag static
Definition at line 112 of file ColorMap.h.
_dataBoundsTag
const string VAPoR::ColorMap::_dataBoundsTag static
Definition at line 115 of file ColorMap.h.
_interpTypeTag
const string VAPoR::ColorMap::_interpTypeTag static
Definition at line 113 of file ColorMap.h.
_useWhitespaceTag
const string VAPoR::ColorMap::_useWhitespaceTag static
Definition at line 114 of file ColorMap.h.
The documentation for this class was generated from the following file:
/Users/pearse/VAPOR/include/vapor/ColorMap.h