version: "2"

  #apt_packages:
  #  - 
build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-22.9"
  jobs:
    pre_build:
    - ls $READTHEDOCS_REPOSITORY_PATH
    - ls $CONDA_ENVS_PATH
    - ls $CONDA_ENVS_PATH/$READTHEDOCS_GIT_BRANCH
    - echo $CONDA_ENVS_PATH
    - echo $READTHEDOCS_GIT_BRANCH
    - cp $READTHEDOCS_REPOSITORY_PATH/config.py $CONDA_ENVS_PATH/$READTHEDOCS_GIT_BRANCH/lib/python3.9/site-packages/vapor
    #- mkdir -p _readthedocs/_static
    #- cp -r $READTHEDOCS_REPOSITORY_PATH/docs/_static/vaporClassReference _readthedocs/_static
    - mkdir -p $READTHEDOCS_OUTPUT/html/vaporApplicationReference
    - cp -r $READTHEDOCS_REPOSITORY_PATH/docs/_static/vaporClassReference $READTHEDOCS_OUTPUT/html/vaporApplicationReference
    #- cp $READTHEDOCS_REPOSITORY_PATH/docs/_static/vaporClassReference/index.html $READTHEDOCS_OUTPUT/html/vaporApplicationReference
    post_build:
    - conda env export --from-history
    - export CONDA_PREFIX=/home/docs/checkouts/readthedocs.org/user_builds/vapordocumentationwebsite/conda/$READTHEDOCS_GIT_BRANCH
    - python -c "from vapor import animation"
    - ls $READTHEDOCS_REPOSITORY_PATH
    - ls $READTHEDOCS_REPOSITORY_PATH/vaporApplicationReference
    - ls $READTHEDOCS_REPOSITORY_PATH/vaporApplicationReference/vaporClassReference
    - ls $READTHEDOCS_OUTPUT
    - ls $READTHEDOCS_OUTPUT/html
    - ls $READTHEDOCS_OUTPUT/html/vaporApplicationReference
    - echo $READTHEDOCS_OUTPUT/html/vaporApplicationReference
    - ls $READTHEDOCS_OUTPUT/html/vaporApplicationReference/vaporClassReference
    - ls
    - pwd
    #- ls _static
    #- ls _readthedocs
    #- ls _readthedocs/html
    #- ls _readthedocs/html/_static
    #- ls _readthedocs/html/_static/vaporClassReference
    #- ls $READTHEDOCS_OUTPUT/html/_static/vaporClassReference/vaporApplicationReference


sphinx:
  configuration: docs/conf.py
  #configuration: docs/source/conf.py

conda:
  environment: environment.yml
