version: "2"

  #apt_packages:
  #  - 
build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-22.9"
  jobs:
    pre_build:
    - conda env list
    #- curl -O https://github.com/NCAR/VAPOR/blob/main/apps/pythonapi/vapor/config.py
    #- cp config.py $CONDA_ENVS_PATH/$READTHEDOCS_VERSION/lib/python3.9/site-packages/vapor
    - cp $READTHEDOCS_REPOSITORY_PATH/config.py $CONDA_ENVS_PATH/$READTHEDOCS_VERSION/lib/python3.9/site-packages/vapor
    - mkdir -p $READTHEDOCS_OUTPUT/html/vaporApplicationReference
    - cp -r $READTHEDOCS_REPOSITORY_PATH/docs/_static/vaporClassReference $READTHEDOCS_OUTPUT/html/vaporApplicationReference
    post_build:
    - python -c "from vapor import animation"


sphinx:
  configuration: docs/conf.py
  #configuration: docs/source/conf.py

conda:
  environment: environment.yml
