version: "2"

  #apt_packages:
  #  - 
build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-22.9"
  jobs:
    pre_build:
    - cp $READTHEDOCS_REPOSITORY_PATH/config.py $CONDA_ENVS_PATH/latest/lib/python3.9/site-packages/vapor
    - mkdir -p _readTheDocs/_static
    - cp -r $READTHEDOCS_REPOSITORY_PATH/docs/_static/vaporClassReference _readTheDocs/_static
    post_build:
    - conda env export --from-history
    - export CONDA_PREFIX=/home/docs/checkouts/readthedocs.org/user_builds/vapordocumentationwebsite/conda/latest
    - python -c "from vapor import animation"
    - ls $READTHEDOCS_REPOSITORY_PATH
    - ls $READTHEDOCS_REPOSITORY_PATH/vaporApplicationReference
    - ls $READTHEDOCS_REPOSITORY_PATH/vaporApplicationReference/vaporClassReference
    - ls $READTHEDOCS_OUTPUT
    - ls $READTHEDOCS_OUTPUT/html
    - ls $READTHEDOCS_OUTPUT/html/vaporApplicationReference
    - echo $READTHEDOCS_OUTPUT/html/vaporApplicationReference
    - ls $READTHEDOCS_OUTPUT/html/_static
    - ls $READTHEDOCS_OUTPUT/html/_static/vaporClassReference
    - ls _readTheDocs/_static
    - ls _readTheDocs
    - ls
    - pwd
    #- ls $READTHEDOCS_OUTPUT/html/_static/vaporClassReference/vaporApplicationReference


sphinx:
  configuration: docs/conf.py
  #configuration: docs/source/conf.py

conda:
  environment: environment.yml
