VAPOR3: RangeCombo Class Reference
RangeCombo Class Reference
#include <RangeCombos.h>
Public Slots
void setValueMin (double)
void setValueMax (double)
Signals
void valueChanged (double minValue, double maxValue)
Public Member Functions
RangeCombo (Combo *minWidget, Combo *maxWidget)
void Update (double minValid, double maxValid, double minValue, double maxValue)
QSlider * GetSliderMin () const
QLineEdit * GetLineEditMin () const
QSlider * GetSliderMax () const
QLineEdit * GetLineEditMax () const
Detailed Description
Definition at line 34 of file RangeCombos.h.
Constructor & Destructor Documentation
RangeCombo()
RangeCombo::RangeCombo (Combo * minWidget, Combo * maxWidget)
Member Function Documentation
GetLineEditMax()
QLineEdit * RangeCombo::GetLineEditMax () const inline
Definition at line 54 of file RangeCombos.h.
References Combo::GetLineEdit().
GetLineEditMin()
QLineEdit * RangeCombo::GetLineEditMin () const inline
Definition at line 51 of file RangeCombos.h.
References Combo::GetLineEdit().
GetSliderMax()
QSlider * RangeCombo::GetSliderMax () const inline
Definition at line 53 of file RangeCombos.h.
References Combo::GetSlider().
GetSliderMin()
QSlider * RangeCombo::GetSliderMin () const inline
Definition at line 50 of file RangeCombos.h.
References Combo::GetSlider().
setValueMax
void RangeCombo::setValueMax (double) slot
setValueMin
void RangeCombo::setValueMin (double) slot
Update()
void RangeCombo::Update (double minValid, double maxValid, double minValue, double maxValue)
valueChanged
void RangeCombo::valueChanged (double minValue, double maxValue) signal
The documentation for this class was generated from the following file:
/Users/pearse/VAPOR/apps/vaporgui/RangeCombos.h