VAPOR3: NavigationUtils Class Reference
NavigationUtils Class Reference
This class is just migrated legacy code to de-spaghetti other legacy code. (It is not written by me)
#include <NavigationUtils.h>
Static Public Member Functions
static void SetHomeViewpoint (ControlExec *ce)
static void UseHomeViewpoint (ControlExec *ce)
static void ViewAll (ControlExec *ce)
static void AlignView (ControlExec *ce, int axis)
static void SetAllCameras (ControlExec *ce, const double position[3], const double direction[3], const double up[3], const double origin[3])
static void SetAllCameras (ControlExec *ce, const double position[3], const double direction[3], const double up[3])
static void SetAllCameras (ControlExec *ce, const vector< double > &position, const vector< double > &direction, const vector< double > &up, const vector< double > &origin)
static void SetAllCameras (ControlExec *ce, const vector< double > &position, const vector< double > &direction, const vector< double > &up)
static void SetAllCameras (ControlExec *ce, const double matrix[16], const double origin[3])
static void SetAllCameras (ControlExec *ce, const vector< double > &matrix, const vector< double > &origin)
static void SetAllCameras (ControlExec *ce, const Trackball &trackball)
static void ConfigureTrackball (ControlExec *ce, Trackball &trackball)
static void LookAt (ControlExec *ce, const vector< double > &position, const vector< double > &target, const vector< double > &up)
static void SetTimestep (ControlExec *ce, size_t ts)
static void GetCameraProperties (ControlExec *ce, vector< double > *position, vector< double > *direction, vector< double > *up, vector< double > *target)
static vector< double > GetCameraPosition (ControlExec *ce)
static vector< double > GetCameraDirection (ControlExec *ce)
static vector< double > GetCameraUp (ControlExec *ce)
static vector< double > GetCameraTarget (ControlExec *ce)
static void SetCameraPosition (ControlExec *ce, const vector< double > &v)
static void SetCameraDirection (ControlExec *ce, const vector< double > &v)
static void SetCameraUp (ControlExec *ce, const vector< double > &v)
static void SetCameraTarget (ControlExec *ce, const vector< double > &v)
static long GetCurrentTimeStep (ControlExec *ce)
static VAPoR::ViewpointParams * GetActiveViewpointParams (ControlExec *ce)
static GUIStateParams * GetGUIStateParams (ControlExec *ce)
static AnimationParams * GetAnimationParams (ControlExec *ce)
Static Public Member Functions inherited from Wasp::MyBase
static void SetErrMsg (const char *format,...)
Record a formatted error message.
static void SetErrMsg (int errcode, const char *format,...)
Record a formatted error message and an error code.
static const char * GetErrMsg ()
static void SetErrCode (int err_code)
Record an error code.
static int GetErrCode ()
Retrieve the current error code.
static void SetErrMsgCB (ErrMsgCB_T cb)
static ErrMsgCB_T GetErrMsgCB ()
static void SetErrMsgFilePtr (FILE *fp)
static const FILE * SetErrMsgFilePtr ()
static void SetDiagMsg (const char *format,...)
Record a formatted diagnostic message.
static const char * GetDiagMsg ()
static void SetDiagMsgCB (DiagMsgCB_T cb)
static DiagMsgCB_T GetDiagMsgCB ()
static void SetDiagMsgFilePtr (FILE *fp)
static bool EnableErrMsg (bool enable)
static bool GetEnableErrMsg ()
Additional Inherited Members
Public Types inherited from Wasp::MyBase
typedef void(* ErrMsgCB_T) (const char *msg, int err_code)
typedef void(* DiagMsgCB_T) (const char *msg)
Public Member Functions inherited from Wasp::MyBase
MyBase ()
const string & getClassName () const
Static Public Attributes inherited from Wasp::MyBase
static char * ErrMsg
static int ErrCode
static int ErrMsgSize
static FILE * ErrMsgFilePtr
static ErrMsgCB_T ErrMsgCB
static char * DiagMsg
static int DiagMsgSize
static FILE * DiagMsgFilePtr
static DiagMsgCB_T DiagMsgCB
static bool Enabled
Protected Member Functions inherited from Wasp::MyBase
void SetClassName (const string &name)
Detailed Description
This class is just migrated legacy code to de-spaghetti other legacy code. (It is not written by me)
Definition at line 17 of file NavigationUtils.h.
Member Function Documentation
AlignView()
static void NavigationUtils::AlignView (ControlExec * ce, int axis) static
Align the view direction to one of the axes. axis is 2,3,4 for +X,Y,Z, and 5,6,7 for -X,-Y,-Z
Referenced by TabManager::AlignView().
ConfigureTrackball()
static void NavigationUtils::ConfigureTrackball (ControlExec * ce, Trackball & trackball) static
GetActiveViewpointParams()
static VAPoR::ViewpointParams * NavigationUtils::GetActiveViewpointParams (ControlExec * ce) static
GetAnimationParams()
static AnimationParams * NavigationUtils::GetAnimationParams (ControlExec * ce) static
GetCameraDirection()
static vector< double > NavigationUtils::GetCameraDirection (ControlExec * ce) static
GetCameraPosition()
static vector< double > NavigationUtils::GetCameraPosition (ControlExec * ce) static
GetCameraProperties()
static void NavigationUtils::GetCameraProperties (ControlExec * ce, vector< double > * position, vector< double > * direction, vector< double > * up, vector< double > * target) static
GetCameraTarget()
static vector< double > NavigationUtils::GetCameraTarget (ControlExec * ce) static
GetCameraUp()
static vector< double > NavigationUtils::GetCameraUp (ControlExec * ce) static
GetCurrentTimeStep()
static long NavigationUtils::GetCurrentTimeStep (ControlExec * ce) static
GetGUIStateParams()
static GUIStateParams * NavigationUtils::GetGUIStateParams (ControlExec * ce) static
LookAt()
static void NavigationUtils::LookAt (ControlExec * ce, const vector< double > & position, const vector< double > & target, const vector< double > & up) static
SetAllCameras() [1/7]
static void NavigationUtils::SetAllCameras (ControlExec * ce, const double matrix[16], const double origin[3]) static
SetAllCameras() [2/7]
static void NavigationUtils::SetAllCameras (ControlExec * ce, const double position[3], const double direction[3], const double up[3]) static
SetAllCameras() [3/7]
static void NavigationUtils::SetAllCameras (ControlExec * ce, const double position[3], const double direction[3], const double up[3], const double origin[3]) static
SetAllCameras() [4/7]
static void NavigationUtils::SetAllCameras (ControlExec * ce, const Trackball & trackball) static
SetAllCameras() [5/7]
static void NavigationUtils::SetAllCameras (ControlExec * ce, const vector< double > & matrix, const vector< double > & origin) static
SetAllCameras() [6/7]
static void NavigationUtils::SetAllCameras (ControlExec * ce, const vector< double > & position, const vector< double > & direction, const vector< double > & up) static
SetAllCameras() [7/7]
static void NavigationUtils::SetAllCameras (ControlExec * ce, const vector< double > & position, const vector< double > & direction, const vector< double > & up, const vector< double > & origin) static
SetCameraDirection()
static void NavigationUtils::SetCameraDirection (ControlExec * ce, const vector< double > & v) static
SetCameraPosition()
static void NavigationUtils::SetCameraPosition (ControlExec * ce, const vector< double > & v) static
SetCameraTarget()
static void NavigationUtils::SetCameraTarget (ControlExec * ce, const vector< double > & v) static
SetCameraUp()
static void NavigationUtils::SetCameraUp (ControlExec * ce, const vector< double > & v) static
SetHomeViewpoint()
static void NavigationUtils::SetHomeViewpoint (ControlExec * ce) static
Referenced by TabManager::SetHomeViewpoint().
SetTimestep()
static void NavigationUtils::SetTimestep (ControlExec * ce, size_t ts) static
UseHomeViewpoint()
static void NavigationUtils::UseHomeViewpoint (ControlExec * ce) static
Referenced by TabManager::UseHomeViewpoint().
ViewAll()
static void NavigationUtils::ViewAll (ControlExec * ce) static
Referenced by TabManager::ViewAll().
The documentation for this class was generated from the following file:
/Users/pearse/VAPOR/include/vapor/NavigationUtils.h