VAPOR3: ViewpointTab Class Reference
ViewpointTab Class Reference
#include <ViewpointTab.h>
Signals
void Proj4StringChanged (string proj4String)
Public Member Functions
ViewpointTab (VAPoR::ControlExec *ce)
virtual ~ViewpointTab ()
string GetType () const
virtual void updateTab ()
virtual void _updateTab ()
Public Member Functions inherited from EventRouter
EventRouter (VAPoR::ControlExec *ce, string paramsType)
virtual ~EventRouter ()
virtual VAPoR::ParamsBase * GetActiveParams () const
virtual void hookUpTab ()
virtual void GetWebHelp (std::vector< std::pair< string, string > > &help) const
virtual void updateTab ()
virtual void confirmText ()
void SetTextChanged (bool on)
virtual void captureMouseUp ()
virtual void captureMouseDown (int mouseNum)
virtual void StartCursorMove ()
virtual void EndCursorMove ()
GUIStateParams * GetStateParams () const
AnimationParams * GetAnimationParams () const
size_t GetCurrentTimeStep () const
virtual string GetType () const =0
virtual void LoadDataNotify (string dataSetName)
Static Public Member Functions
static string GetClassType ()
Static Public Member Functions inherited from EventRouter
static size_t GetCurrentTimeStep (VAPoR::ControlExec *ce)
Additional Inherited Members
Protected Member Functions inherited from EventRouter
EventRouter ()
virtual void _initializeTab ()
virtual void _updateTab ()=0
virtual void _confirmText ()
Protected Attributes inherited from EventRouter
VAPoR::ControlExec * _controlExec
bool _textChangedFlag
string _paramsType
Detailed Description
Definition at line 10 of file ViewpointTab.h.
Constructor & Destructor Documentation
ViewpointTab()
ViewpointTab::ViewpointTab (VAPoR::ControlExec * ce)
~ViewpointTab()
virtual ViewpointTab::~ViewpointTab () inline virtual
Definition at line 18 of file ViewpointTab.h.
Member Function Documentation
_updateTab()
virtual void ViewpointTab::_updateTab () virtual
Pure virtual method to set the values of all the gui elements in the tab based on current Params state. This is invoked whenever the tab is redisplayed and the values in the tab need to be refreshed. If there is a VariablesWidget, _updateTab() must invoke VariablesWidget::Update().
Implements EventRouter.
Referenced by updateTab().
GetClassType()
static string ViewpointTab::GetClassType () inline static
Definition at line 20 of file ViewpointTab.h.
Referenced by GetType().
GetType()
string ViewpointTab::GetType () const inline virtual
Return derived class type
Return a string identifier for the derived EventRouter type
Implements EventRouter.
Definition at line 21 of file ViewpointTab.h.
References GetClassType().
Proj4StringChanged
void ViewpointTab::Proj4StringChanged (string proj4String) signal
updateTab()
virtual void ViewpointTab::updateTab () inline virtual
Update GUI display
This method set the values of all the gui elements in the tab based on current Params state. This will do appropriate setup and then invoke the pure virtual method _updateTab(). This is invoked whenever the tab is redisplayed and the values in the tab need to be refreshed.
The method has three responsibilities:
Reconcile any anomalous conditions between the DataMgr and the Params instance managed by this event router. Thus if the Params instance contains values that would be viable with the current DataMgr (e.g. a variable name that is not present in the DataMgr) the method will attempt to change the Params instance to a valid state.
Refresh (rebuild) the GUI to reflect the state of the Params.
Ensure that the options presented by the GUI are viable for the current DataMgr.
Reimplemented from EventRouter.
Definition at line 23 of file ViewpointTab.h.
References _updateTab().
The documentation for this class was generated from the following file:
/Users/pearse/VAPOR/apps/vaporgui/ViewpointTab.h