VAPOR3: AnimationParams Class Reference
AnimationParams Class Reference
VAPOR Params Developer API
A class that specifies parameters used in animation.
#include <AnimationParams.h>
Public Member Functions
AnimationParams (ParamsBase::StateSave *ssave)
AnimationParams (VAPoR::ParamsBase::StateSave *ssave, VAPoR::XmlNode *node)
virtual ~AnimationParams ()
size_t GetCurrentTimestep () const
void SetCurrentTimestep (size_t ts)
size_t GetStartTimestep () const
void SetStartTimestep (size_t ts)
size_t GetEndTimestep () const
void SetEndTimestep (size_t val)
bool GetPlayBackwards () const
void SetPlayBackwards (bool val)
size_t GetFrameStepSize () const
void SetFrameStepSize (size_t val)
double GetMaxFrameRate ()
void SetMaxFrameRate (double rate)
bool GetRepeating () const
void SetRepeating (bool onOff)
Public Member Functions inherited from VAPoR::ParamsBase
ParamsBase (StateSave *ssave, const string &classname)
ParamsBase (StateSave *ssave, XmlNode *node)
ParamsBase (const ParamsBase &rhs)
Copy constructor.
ParamsBase & operator= (const ParamsBase &rhs)
ParamsBase (ParamsBase &&)=delete
ParamsBase & operator= (ParamsBase &)=delete
bool operator== (const ParamsBase &rhs) const
Equivalence operator.
bool operator!= (const ParamsBase &rhs) const
virtual ~ParamsBase ()
void SetParent (ParamsBase *parent)
XmlNode * GetNode () const
void BeginGroup (const string &description)
void EndGroup ()
void IntermediateChange ()
virtual vector< long > GetValueLongVec (const string tag) const
virtual vector< long > GetValueLongVec (const string tag, const vector< long > &defaultVal) const
virtual long GetValueLong (const string tag, long defaultVal) const
virtual vector< double > GetValueDoubleVec (const string tag) const
virtual vector< double > GetValueDoubleVec (const string tag, const vector< double > &defaultVal) const
virtual double GetValueDouble (const string tag, double defaultVal) const
virtual vector< string > GetValueStringVec (const string tag) const
virtual vector< string > GetValueStringVec (const string tag, const vector< string > &defaultVal) const
virtual string GetValueString (const string tag, string defaultVal) const
virtual void SetValueLongVec (const string &tag, string description, const vector< long > &values)
virtual void SetValueLong (const string &tag, string description, long value)
virtual void SetValueDoubleVec (const string &tag, string description, const vector< double > &values)
virtual void SetValueDouble (const string &tag, string description, double value)
virtual void SetValueStringVec (const string &tag, string description, const vector< string > &values)
virtual void SetValueString (const string &tag, string description, const string &value)
string GetName () const
Public Member Functions inherited from Wasp::MyBase
MyBase ()
const string & getClassName () const
Static Public Member Functions
static string GetClassType ()
Static Public Member Functions inherited from Wasp::MyBase
static void SetErrMsg (const char *format,...)
Record a formatted error message.
static void SetErrMsg (int errcode, const char *format,...)
Record a formatted error message and an error code.
static const char * GetErrMsg ()
static void SetErrCode (int err_code)
Record an error code.
static int GetErrCode ()
Retrieve the current error code.
static void SetErrMsgCB (ErrMsgCB_T cb)
static ErrMsgCB_T GetErrMsgCB ()
static void SetErrMsgFilePtr (FILE *fp)
static const FILE * SetErrMsgFilePtr ()
static void SetDiagMsg (const char *format,...)
Record a formatted diagnostic message.
static const char * GetDiagMsg ()
static void SetDiagMsgCB (DiagMsgCB_T cb)
static DiagMsgCB_T GetDiagMsgCB ()
static void SetDiagMsgFilePtr (FILE *fp)
static bool EnableErrMsg (bool enable)
static bool GetEnableErrMsg ()
Static Public Attributes
static const string _repeatTag
static const string _maxRateTag
static const string _stepSizeTag
static const string _startTimestepTag
static const string _endTimestepTag
static const string _playBackwardsTag
static const string _currentTimestepTag
Static Public Attributes inherited from Wasp::MyBase
static char * ErrMsg
static int ErrCode
static int ErrMsgSize
static FILE * ErrMsgFilePtr
static ErrMsgCB_T ErrMsgCB
static char * DiagMsg
static int DiagMsgSize
static FILE * DiagMsgFilePtr
static DiagMsgCB_T DiagMsgCB
static bool Enabled
Additional Inherited Members
Public Types inherited from Wasp::MyBase
typedef void(* ErrMsgCB_T) (const char *msg, int err_code)
typedef void(* DiagMsgCB_T) (const char *msg)
Protected Member Functions inherited from VAPoR::ParamsBase
ParamsBase (StateSave *ssave)
void Remove (const string &name)
const map< string, string > & GetAttributes ()
void Clear ()
Protected Member Functions inherited from Wasp::MyBase
void SetClassName (const string &name)
Protected Attributes inherited from VAPoR::ParamsBase
StateSave * _ssave
XmlNode * _node
Detailed Description
A class that specifies parameters used in animation.
When this class is local, it controls the time-steps in one visualizer. The global (shared) AnimationParams controls the animation in any number of visualizers.
Author
Alan Norton
Version
3.0
Date
February 2014
Definition at line 37 of file AnimationParams.h.
Constructor & Destructor Documentation
AnimationParams() [1/2]
AnimationParams::AnimationParams (ParamsBase::StateSave * ssave)
AnimationParams() [2/2]
AnimationParams::AnimationParams (VAPoR::ParamsBase::StateSave * ssave, VAPoR::XmlNode * node)
~AnimationParams()
virtual AnimationParams::~AnimationParams () virtual
Member Function Documentation
GetClassType()
static string AnimationParams::GetClassType () inline static
Definition at line 126 of file AnimationParams.h.
Referenced by EventRouter::GetAnimationParams(), and EventRouter::GetCurrentTimeStep().
GetCurrentTimestep()
size_t AnimationParams::GetCurrentTimestep () const inline
Identify the current data timestep being used
Return values
long current time step
Definition at line 48 of file AnimationParams.h.
References VAPoR::ParamsBase::GetValueLong().
Referenced by EventRouter::GetCurrentTimeStep().
GetEndTimestep()
size_t AnimationParams::GetEndTimestep () const inline
Identify the ending time step used during playback
Return values
int ending timestep
Definition at line 73 of file AnimationParams.h.
References VAPoR::ParamsBase::GetValueLong().
GetFrameStepSize()
size_t AnimationParams::GetFrameStepSize () const inline
Get the maximum frame step size for skipping
Return values
int current frame step size.
Definition at line 94 of file AnimationParams.h.
References VAPoR::ParamsBase::GetValueLong().
GetMaxFrameRate()
double AnimationParams::GetMaxFrameRate () inline
Determine max frames per second
Return values
double max frames per second
Definition at line 105 of file AnimationParams.h.
References VAPoR::ParamsBase::GetValueDouble().
GetPlayBackwards()
bool AnimationParams::GetPlayBackwards () const inline
Get the current play direction
Return values
bool True if playing backwards
Definition at line 84 of file AnimationParams.h.
References VAPoR::ParamsBase::GetValueLong().
GetRepeating()
bool AnimationParams::GetRepeating () const inline
Determine if repeat play is on
Return values
bool true if repeating
Definition at line 116 of file AnimationParams.h.
References VAPoR::ParamsBase::GetValueLong().
GetStartTimestep()
size_t AnimationParams::GetStartTimestep () const inline
Identify the starting time step currently set in the UI.
Return values
int starting frame number.
Definition at line 62 of file AnimationParams.h.
References VAPoR::ParamsBase::GetValueLong().
SetCurrentTimestep()
void AnimationParams::SetCurrentTimestep (size_t ts) inline
Set the current data timestep being used
Parameters
long current time step
Return values
int 0 if successful
Definition at line 54 of file AnimationParams.h.
References VAPoR::ParamsBase::SetValueLong().
SetEndTimestep()
void AnimationParams::SetEndTimestep (size_t val) inline
set the ending time step
Parameters
int ending timestep
Return values
int 0 if success
Definition at line 79 of file AnimationParams.h.
References VAPoR::ParamsBase::SetValueLong().
SetFrameStepSize()
void AnimationParams::SetFrameStepSize (size_t val) inline
Set the frame step size (for skipping)
Parameters
int val step size
Return values
int 0 if successful
Definition at line 100 of file AnimationParams.h.
References VAPoR::ParamsBase::SetValueLong().
SetMaxFrameRate()
void AnimationParams::SetMaxFrameRate (double rate) inline
Set max frames per second
Parameters
double fps
Return values
int 0 if successful
Definition at line 111 of file AnimationParams.h.
References VAPoR::ParamsBase::SetValueDouble().
SetPlayBackwards()
void AnimationParams::SetPlayBackwards (bool val) inline
Set the play direction
Parameters
int play direction
Definition at line 89 of file AnimationParams.h.
References VAPoR::ParamsBase::SetValueLong().
SetRepeating()
void AnimationParams::SetRepeating (bool onOff) inline
Set the whether repeat play is on
Parameters
bool repeat is on if true
Return values
int 0 if successful
Definition at line 122 of file AnimationParams.h.
References VAPoR::ParamsBase::SetValueLong().
SetStartTimestep()
void AnimationParams::SetStartTimestep (size_t ts) inline
set the starting time step
Parameters
int starting timestep
Return values
int 0 if successful
Definition at line 68 of file AnimationParams.h.
References VAPoR::ParamsBase::SetValueLong().
Member Data Documentation
_currentTimestepTag
const string AnimationParams::_currentTimestepTag static
Definition at line 135 of file AnimationParams.h.
_endTimestepTag
const string AnimationParams::_endTimestepTag static
Definition at line 133 of file AnimationParams.h.
_maxRateTag
const string AnimationParams::_maxRateTag static
Definition at line 130 of file AnimationParams.h.
_playBackwardsTag
const string AnimationParams::_playBackwardsTag static
Definition at line 134 of file AnimationParams.h.
_repeatTag
const string AnimationParams::_repeatTag static
Definition at line 129 of file AnimationParams.h.
_startTimestepTag
const string AnimationParams::_startTimestepTag static
Definition at line 132 of file AnimationParams.h.
_stepSizeTag
const string AnimationParams::_stepSizeTag static
Definition at line 131 of file AnimationParams.h.
The documentation for this class was generated from the following file:
/Users/pearse/VAPOR/include/vapor/AnimationParams.h