VAPOR3: RenderEventRouterGUI Class Reference
RenderEventRouterGUI Class Reference
VAPOR GUI Developer API
Tab manager for renderer subtabs.
#include <RenderEventRouterGUI.h>
Public Member Functions
RenderEventRouterGUI (VAPoR::ControlExec *ce, string paramsType)
QWidget * AddSubtab (string title, UWidget *subtab)
QWidget * AddVariablesSubtab (UWidget *subtab)
QWidget * AddAppearanceSubtab (UWidget *subtab)
QWidget * AddGeometrySubtab (UWidget *subtab)
QWidget * AddAnnotationSubtab (UWidget *subtab)
Public Member Functions inherited from RenderEventRouter
RenderEventRouter (VAPoR::ControlExec *ce, string paramsType)
virtual ~RenderEventRouter ()
void SetActive (string instName)
virtual void hookUpTab ()
virtual void updateTab ()
virtual void confirmText ()
virtual bool Supports2DVariables () const =0
virtual bool Supports3DVariables () const =0
virtual bool SupportsParticleVariables () const
void updateRenderer (VAPoR::RenderParams *rParams, bool prevEnabled, string VizName, string renderInstName, bool newWindow)
virtual void sessionLoadTF (string name)
virtual void fitToView ()
virtual ColorbarWidget * getColorbarWidget ()
virtual void variableChanged ()
VAPoR::RenderParams * GetActiveParams () const
VAPoR::DataMgr * GetActiveDataMgr () const
string GetDescription () const
string GetSmallIconImagePath () const
string GetIconImagePath () const
Public Member Functions inherited from EventRouter
EventRouter (VAPoR::ControlExec *ce, string paramsType)
virtual ~EventRouter ()
virtual VAPoR::ParamsBase * GetActiveParams () const
virtual void hookUpTab ()
virtual void GetWebHelp (std::vector< std::pair< string, string > > &help) const
virtual void updateTab ()
virtual void confirmText ()
void SetTextChanged (bool on)
virtual void captureMouseUp ()
virtual void captureMouseDown (int mouseNum)
virtual void StartCursorMove ()
virtual void EndCursorMove ()
GUIStateParams * GetStateParams () const
AnimationParams * GetAnimationParams () const
size_t GetCurrentTimeStep () const
virtual string GetType () const =0
virtual void LoadDataNotify (string dataSetName)
Static Public Attributes
static const std::string VariablesTabName
static const std::string AppearanceTabName
static const std::string GeometryTabName
static const std::string AnnotationTabName
Protected Member Functions
virtual void _updateTab () override
Protected Member Functions inherited from RenderEventRouter
RenderEventRouter ()
virtual void _updateTab ()=0
virtual void _confirmText ()
virtual string _getDescription () const =0
virtual string _getSmallIconImagePath () const =0
virtual string _getIconImagePath () const =0
Protected Member Functions inherited from EventRouter
EventRouter ()
virtual void _initializeTab ()
virtual void _updateTab ()=0
virtual void _confirmText ()
Additional Inherited Members
Static Public Member Functions inherited from EventRouter
static size_t GetCurrentTimeStep (VAPoR::ControlExec *ce)
Protected Attributes inherited from EventRouter
VAPoR::ControlExec * _controlExec
bool _textChangedFlag
string _paramsType
Detailed Description
Tab manager for renderer subtabs.
Author
Stas Jaroszynski
Definition at line 14 of file RenderEventRouterGUI.h.
Constructor & Destructor Documentation
RenderEventRouterGUI()
RenderEventRouterGUI::RenderEventRouterGUI (VAPoR::ControlExec * ce, string paramsType)
Member Function Documentation
_updateTab()
virtual void RenderEventRouterGUI::_updateTab () override protected virtual
Pure virtual method to set the values of all the gui elements in the tab based on current Params state. This is invoked whenever the tab is redisplayed and the values in the tab need to be refreshed. If there is a VariablesWidget, _updateTab() must invoke VariablesWidget::updateTab().
Parameters
[in] p Params instance associated with the current active tab.
Implements RenderEventRouter.
Reimplemented in ContourEventRouter, and FlowEventRouter.
AddAnnotationSubtab()
QWidget * RenderEventRouterGUI::AddAnnotationSubtab (UWidget * subtab) inline
Definition at line 28 of file RenderEventRouterGUI.h.
References AddSubtab(), and AnnotationTabName.
AddAppearanceSubtab()
QWidget * RenderEventRouterGUI::AddAppearanceSubtab (UWidget * subtab) inline
Definition at line 26 of file RenderEventRouterGUI.h.
References AddSubtab(), and AppearanceTabName.
AddGeometrySubtab()
QWidget * RenderEventRouterGUI::AddGeometrySubtab (UWidget * subtab) inline
Definition at line 27 of file RenderEventRouterGUI.h.
References AddSubtab(), and GeometryTabName.
AddSubtab()
QWidget * RenderEventRouterGUI::AddSubtab (string title, UWidget * subtab)
Referenced by AddAnnotationSubtab(), AddAppearanceSubtab(), AddGeometrySubtab(), and AddVariablesSubtab().
AddVariablesSubtab()
QWidget * RenderEventRouterGUI::AddVariablesSubtab (UWidget * subtab) inline
Definition at line 25 of file RenderEventRouterGUI.h.
References AddSubtab(), and VariablesTabName.
Member Data Documentation
AnnotationTabName
const std::string RenderEventRouterGUI::AnnotationTabName static
Definition at line 21 of file RenderEventRouterGUI.h.
Referenced by AddAnnotationSubtab().
AppearanceTabName
const std::string RenderEventRouterGUI::AppearanceTabName static
Definition at line 19 of file RenderEventRouterGUI.h.
Referenced by AddAppearanceSubtab().
GeometryTabName
const std::string RenderEventRouterGUI::GeometryTabName static
Definition at line 20 of file RenderEventRouterGUI.h.
Referenced by AddGeometrySubtab().
VariablesTabName
const std::string RenderEventRouterGUI::VariablesTabName static
Definition at line 18 of file RenderEventRouterGUI.h.
Referenced by AddVariablesSubtab().
The documentation for this class was generated from the following file:
/Users/pearse/VAPOR/apps/vaporgui/RenderEventRouterGUI.h