VAPOR3: VAPoR::ParamsContainer Class Reference
VAPoR::ParamsContainer Class Reference
#include <ParamsBase.h>
Public Member Functions
ParamsContainer (ParamsBase::StateSave *ssave, const string &myname)
ParamsContainer (ParamsBase::StateSave *ssave, XmlNode *node)
ParamsContainer (const ParamsContainer &rhs)
Copy constructor.
ParamsContainer & operator= (const ParamsContainer &rhs)
virtual ~ParamsContainer ()
void SetParent (ParamsBase *parent)
ParamsBase * Insert (ParamsBase *pb, string name)
ParamsBase * Create (string classType, string name)
void Remove (string name)
void Remove (const ParamsBase *pb)
ParamsBase * GetParams (string name) const
string GetParamsName (const ParamsBase *pb) const
vector< string > GetNames () const
size_t Size () const
XmlNode * GetNode () const
Public Member Functions inherited from Wasp::MyBase
MyBase ()
const string & getClassName () const
Additional Inherited Members
Public Types inherited from Wasp::MyBase
typedef void(* ErrMsgCB_T) (const char *msg, int err_code)
typedef void(* DiagMsgCB_T) (const char *msg)
Static Public Member Functions inherited from Wasp::MyBase
static void SetErrMsg (const char *format,...)
Record a formatted error message.
static void SetErrMsg (int errcode, const char *format,...)
Record a formatted error message and an error code.
static const char * GetErrMsg ()
static void SetErrCode (int err_code)
Record an error code.
static int GetErrCode ()
Retrieve the current error code.
static void SetErrMsgCB (ErrMsgCB_T cb)
static ErrMsgCB_T GetErrMsgCB ()
static void SetErrMsgFilePtr (FILE *fp)
static const FILE * SetErrMsgFilePtr ()
static void SetDiagMsg (const char *format,...)
Record a formatted diagnostic message.
static const char * GetDiagMsg ()
static void SetDiagMsgCB (DiagMsgCB_T cb)
static DiagMsgCB_T GetDiagMsgCB ()
static void SetDiagMsgFilePtr (FILE *fp)
static bool EnableErrMsg (bool enable)
static bool GetEnableErrMsg ()
Static Public Attributes inherited from Wasp::MyBase
static char * ErrMsg
static int ErrCode
static int ErrMsgSize
static FILE * ErrMsgFilePtr
static ErrMsgCB_T ErrMsgCB
static char * DiagMsg
static int DiagMsgSize
static FILE * DiagMsgFilePtr
static DiagMsgCB_T DiagMsgCB
static bool Enabled
Protected Member Functions inherited from Wasp::MyBase
void SetClassName (const string &name)
Detailed Description
Definition at line 321 of file ParamsBase.h.
Constructor & Destructor Documentation
ParamsContainer() [1/3]
VAPoR::ParamsContainer::ParamsContainer (ParamsBase::StateSave * ssave, const string & myname)
ParamsContainer() [2/3]
VAPoR::ParamsContainer::ParamsContainer (ParamsBase::StateSave * ssave, XmlNode * node)
ParamsContainer() [3/3]
VAPoR::ParamsContainer::ParamsContainer (const ParamsContainer & rhs)
Copy constructor.
~ParamsContainer()
virtual VAPoR::ParamsContainer::~ParamsContainer () virtual
Destroy object
Destroys all resources except possibly the XmlNode associated with this object. If this object's node is a root node (i.e. has no parent) the node is freed. Otherwise it is not
Member Function Documentation
Create()
ParamsBase * VAPoR::ParamsContainer::Create (string classType, string name)
GetNames()
vector< string > VAPoR::ParamsContainer::GetNames () const
GetNode()
XmlNode * VAPoR::ParamsContainer::GetNode () const inline
Definition at line 366 of file ParamsBase.h.
References VAPoR::XmlNode::GetNode().
GetParams()
ParamsBase * VAPoR::ParamsContainer::GetParams (string name) const
GetParamsName()
string VAPoR::ParamsContainer::GetParamsName (const ParamsBase * pb) const
Insert()
ParamsBase * VAPoR::ParamsContainer::Insert (ParamsBase * pb, string name)
operator=()
ParamsContainer & VAPoR::ParamsContainer::operator= (const ParamsContainer & rhs)
Remove() [1/2]
void VAPoR::ParamsContainer::Remove (const ParamsBase * pb) inline
Definition at line 356 of file ParamsBase.h.
References Remove().
Referenced by Remove().
Remove() [2/2]
void VAPoR::ParamsContainer::Remove (string name)
SetParent()
void VAPoR::ParamsContainer::SetParent (ParamsBase * parent) inline
Set parent
This method sets the parent of the ParamsBase class to parent, modifying both this class instance and the parent
Parameters
[in] parent A pointer to a parent ParamsBase class . If NULL the class will become parentless
Definition at line 348 of file ParamsBase.h.
References VAPoR::ParamsBase::GetNode().
Size()
size_t VAPoR::ParamsContainer::Size () const inline
Definition at line 364 of file ParamsBase.h.
The documentation for this class was generated from the following file:
/Users/pearse/VAPOR/include/vapor/ParamsBase.h