VAPOR3: GUIStateParams Class Reference
GUIStateParams Class Reference
#include <GUIStateParams.h>
Classes
class DataSetParam
Public Member Functions
GUIStateParams (VAPoR::ParamsBase::StateSave *ssave)
GUIStateParams (VAPoR::ParamsBase::StateSave *ssave, VAPoR::XmlNode *node)
GUIStateParams (const GUIStateParams &rhs)
GUIStateParams & operator= (const GUIStateParams &rhs)
virtual ~GUIStateParams ()
string GetActiveVizName () const
void SetActiveVizName (string vizWin)
void GetActiveRenderer (string vizWin, string &renderType, string &renderInst) const
Get active renderer class and instance name for a visualizer.
string GetActiveRendererInst () const
void SetActiveRenderer (string vizWin, string renderType, string renderInst)
Get active renderer class and instance name for a visualizer.
string GetActiveDataset () const
void SetActiveDataset (string name)
string GetCurrentSessionFile () const
void SetCurrentSessionFile (string path)
std::vector< string > GetOpenDataSetNames () const
std::vector< string > GetOpenDataSetPaths (string dataSetName) const
std::vector< string > GetOpenDataSetRelativePaths (string dataSetName) const
string GetOpenDataSetFormat (string dataSetName) const
void RemoveOpenDateSet (string dataSetName)
void InsertOpenDateSet (string dataSetName, string format, const std::vector< string > &paths, const std::vector< string > &relPaths={})
void SetOpenDataSets (const std::vector< string > &paths, const std::vector< string > &names)
string GetCurrentImagePath () const
void SetCurrentImagePath (string path)
string GetCurrentImageSavePath () const
void SetCurrentImageSavePath (string path)
string GetCurrentTFPath ()
void SetCurrentTFPath (string path)
string GetCurrentPythonPath () const
void SetCurrentPythonPath (string path)
string GetCurrentFlowPath () const
void SetCurrentFlowPath (string path)
MouseModeParams * GetMouseModeParams () const
std::string GetStatsDatasetName () const
void SetStatsDatasetName (std::string &name)
std::string GetPlotDatasetName () const
void SetPlotDatasetName (std::string &name)
string ActiveTab () const
void SetActiveTab (const string &t)
int GetFlowDimensionality () const
void SetFlowDimensionality (int nDims)
void SetProjectionString (string proj4String)
string GetProjectionString () const
void AddBookmark (BookmarkParams *bookmark)
BookmarkParams * CreateBookmark ()
void SetBookmarks (const vector< BookmarkParams * > &all)
void DeleteBookmark (int i)
void ClearBookmarks ()
vector< BookmarkParams * > GetBookmarks () const
int GetNumBookmarks () const
BookmarkParams * GetBookmark (int i) const
Public Member Functions inherited from VAPoR::ParamsBase
ParamsBase (StateSave *ssave, const string &classname)
ParamsBase (StateSave *ssave, XmlNode *node)
ParamsBase (const ParamsBase &rhs)
Copy constructor.
ParamsBase & operator= (const ParamsBase &rhs)
ParamsBase (ParamsBase &&)=delete
ParamsBase & operator= (ParamsBase &)=delete
bool operator== (const ParamsBase &rhs) const
Equivalence operator.
bool operator!= (const ParamsBase &rhs) const
virtual ~ParamsBase ()
void SetParent (ParamsBase *parent)
XmlNode * GetNode () const
void BeginGroup (const string &description)
void EndGroup ()
void IntermediateChange ()
virtual vector< long > GetValueLongVec (const string tag) const
virtual vector< long > GetValueLongVec (const string tag, const vector< long > &defaultVal) const
virtual long GetValueLong (const string tag, long defaultVal) const
virtual vector< double > GetValueDoubleVec (const string tag) const
virtual vector< double > GetValueDoubleVec (const string tag, const vector< double > &defaultVal) const
virtual double GetValueDouble (const string tag, double defaultVal) const
virtual vector< string > GetValueStringVec (const string tag) const
virtual vector< string > GetValueStringVec (const string tag, const vector< string > &defaultVal) const
virtual string GetValueString (const string tag, string defaultVal) const
virtual void SetValueLongVec (const string &tag, string description, const vector< long > &values)
virtual void SetValueLong (const string &tag, string description, long value)
virtual void SetValueDoubleVec (const string &tag, string description, const vector< double > &values)
virtual void SetValueDouble (const string &tag, string description, double value)
virtual void SetValueStringVec (const string &tag, string description, const vector< string > &values)
virtual void SetValueString (const string &tag, string description, const string &value)
string GetName () const
Public Member Functions inherited from Wasp::MyBase
MyBase ()
const string & getClassName () const
Static Public Member Functions
static string GetClassType ()
Static Public Member Functions inherited from Wasp::MyBase
static void SetErrMsg (const char *format,...)
Record a formatted error message.
static void SetErrMsg (int errcode, const char *format,...)
Record a formatted error message and an error code.
static const char * GetErrMsg ()
static void SetErrCode (int err_code)
Record an error code.
static int GetErrCode ()
Retrieve the current error code.
static void SetErrMsgCB (ErrMsgCB_T cb)
static ErrMsgCB_T GetErrMsgCB ()
static void SetErrMsgFilePtr (FILE *fp)
static const FILE * SetErrMsgFilePtr ()
static void SetDiagMsg (const char *format,...)
Record a formatted diagnostic message.
static const char * GetDiagMsg ()
static void SetDiagMsgCB (DiagMsgCB_T cb)
static DiagMsgCB_T GetDiagMsgCB ()
static void SetDiagMsgFilePtr (FILE *fp)
static bool EnableErrMsg (bool enable)
static bool GetEnableErrMsg ()
Static Public Attributes
static const string m_activeVisualizer
static const string m_pathParamsTag
static const string m_sessionFileTag
static const string m_imagePathTag
static const string m_imageSavePathTag
static const string m_pythonPathTag
static const string m_flowPathTag
static const string m_tfPathTag
static const string m_statsDatasetNameTag
static const string m_plotDatasetNameTag
static const string m_proj4StringTag
static const string m_openDataSetsTag
static const string _flowDimensionalityTag
static const string BookmarksTag
static const string MovingDomainTrackCameraTag
static const string MovingDomainTrackRenderRegionsTag
Static Public Attributes inherited from Wasp::MyBase
static char * ErrMsg
static int ErrCode
static int ErrMsgSize
static FILE * ErrMsgFilePtr
static ErrMsgCB_T ErrMsgCB
static char * DiagMsg
static int DiagMsgSize
static FILE * DiagMsgFilePtr
static DiagMsgCB_T DiagMsgCB
static bool Enabled
Additional Inherited Members
Public Types inherited from Wasp::MyBase
typedef void(* ErrMsgCB_T) (const char *msg, int err_code)
typedef void(* DiagMsgCB_T) (const char *msg)
Protected Member Functions inherited from VAPoR::ParamsBase
ParamsBase (StateSave *ssave)
void Remove (const string &name)
const map< string, string > & GetAttributes ()
void Clear ()
Protected Member Functions inherited from Wasp::MyBase
void SetClassName (const string &name)
Protected Attributes inherited from VAPoR::ParamsBase
StateSave * _ssave
XmlNode * _node
Detailed Description
Definition at line 27 of file GUIStateParams.h.
Constructor & Destructor Documentation
GUIStateParams() [1/3]
GUIStateParams::GUIStateParams (VAPoR::ParamsBase::StateSave * ssave)
GUIStateParams() [2/3]
GUIStateParams::GUIStateParams (VAPoR::ParamsBase::StateSave * ssave, VAPoR::XmlNode * node)
GUIStateParams() [3/3]
GUIStateParams::GUIStateParams (const GUIStateParams & rhs)
~GUIStateParams()
virtual GUIStateParams::~GUIStateParams () virtual
Member Function Documentation
ActiveTab()
string GUIStateParams::ActiveTab () const
AddBookmark()
void GUIStateParams::AddBookmark (BookmarkParams * bookmark)
ClearBookmarks()
void GUIStateParams::ClearBookmarks ()
CreateBookmark()
BookmarkParams * GUIStateParams::CreateBookmark ()
DeleteBookmark()
void GUIStateParams::DeleteBookmark (int i)
GetActiveDataset()
string GUIStateParams::GetActiveDataset () const
GetActiveRenderer()
void GUIStateParams::GetActiveRenderer (string vizWin, string & renderType, string & renderInst) const
Get active renderer class and instance name for a visualizer.
GetActiveRendererInst()
string GUIStateParams::GetActiveRendererInst () const
GetActiveVizName()
string GUIStateParams::GetActiveVizName () const
GetBookmark()
BookmarkParams * GUIStateParams::GetBookmark (int i) const
GetBookmarks()
vector< BookmarkParams * > GUIStateParams::GetBookmarks () const
GetClassType()
static string GUIStateParams::GetClassType () inline static
Definition at line 175 of file GUIStateParams.h.
Referenced by EventRouter::GetStateParams().
GetCurrentFlowPath()
string GUIStateParams::GetCurrentFlowPath () const
method identifies the current session file
Return values
session file path
GetCurrentImagePath()
string GUIStateParams::GetCurrentImagePath () const
method identifies the current session file
Return values
session file path
GetCurrentImageSavePath()
string GUIStateParams::GetCurrentImageSavePath () const
method identifies the current session file
Return values
session file path
GetCurrentPythonPath()
string GUIStateParams::GetCurrentPythonPath () const
method identifies the current session file
Return values
session file path
GetCurrentSessionFile()
string GUIStateParams::GetCurrentSessionFile () const
method identifies the current session file
Return values
session file path
GetCurrentTFPath()
string GUIStateParams::GetCurrentTFPath ()
method identifies the current session file
Return values
session file path
GetFlowDimensionality()
int GUIStateParams::GetFlowDimensionality () const
GetMouseModeParams()
MouseModeParams * GUIStateParams::GetMouseModeParams () const
GetNumBookmarks()
int GUIStateParams::GetNumBookmarks () const
GetOpenDataSetFormat()
string GUIStateParams::GetOpenDataSetFormat (string dataSetName) const
GetOpenDataSetNames()
std::vector< string > GUIStateParams::GetOpenDataSetNames () const inline
Get names of currently opened data sets
Definition at line 64 of file GUIStateParams.h.
GetOpenDataSetPaths()
std::vector< string > GUIStateParams::GetOpenDataSetPaths (string dataSetName) const
GetOpenDataSetRelativePaths()
std::vector< string > GUIStateParams::GetOpenDataSetRelativePaths (string dataSetName) const
GetPlotDatasetName()
std::string GUIStateParams::GetPlotDatasetName () const
method sets and gets the active data set name in Plot utility
GetProjectionString()
string GUIStateParams::GetProjectionString () const inline
Definition at line 139 of file GUIStateParams.h.
References VAPoR::ParamsBase::GetValueString().
GetStatsDatasetName()
std::string GUIStateParams::GetStatsDatasetName () const
method sets and gets the active data set name in Statistics
InsertOpenDateSet()
void GUIStateParams::InsertOpenDateSet (string dataSetName, string format, const std::vector< string > & paths, const std::vector< string > & relPaths = {})
operator=()
GUIStateParams & GUIStateParams::operator= (const GUIStateParams & rhs)
RemoveOpenDateSet()
void GUIStateParams::RemoveOpenDateSet (string dataSetName) inline
Definition at line 71 of file GUIStateParams.h.
SetActiveDataset()
void GUIStateParams::SetActiveDataset (string name)
SetActiveRenderer()
void GUIStateParams::SetActiveRenderer (string vizWin, string renderType, string renderInst)
Get active renderer class and instance name for a visualizer.
SetActiveTab()
void GUIStateParams::SetActiveTab (const string & t)
SetActiveVizName()
void GUIStateParams::SetActiveVizName (string vizWin)
SetBookmarks()
void GUIStateParams::SetBookmarks (const vector< BookmarkParams * > & all)
SetCurrentFlowPath()
void GUIStateParams::SetCurrentFlowPath (string path)
method sets the current session path
Parameters
[in] path string
SetCurrentImagePath()
void GUIStateParams::SetCurrentImagePath (string path)
method sets the current session path
Parameters
[in] path string
SetCurrentImageSavePath()
void GUIStateParams::SetCurrentImageSavePath (string path)
method sets the current session path
Parameters
[in] path string
SetCurrentPythonPath()
void GUIStateParams::SetCurrentPythonPath (string path)
method sets the current session path
Parameters
[in] path string
SetCurrentSessionFile()
void GUIStateParams::SetCurrentSessionFile (string path)
method sets the current session file path
Parameters
[in] path string
SetCurrentTFPath()
void GUIStateParams::SetCurrentTFPath (string path)
method sets the current session path
Parameters
[in] path string
SetFlowDimensionality()
void GUIStateParams::SetFlowDimensionality (int nDims)
SetOpenDataSets()
void GUIStateParams::SetOpenDataSets (const std::vector< string > & paths, const std::vector< string > & names)
method sets the current session path
Parameters
[in] path string
SetPlotDatasetName()
void GUIStateParams::SetPlotDatasetName (std::string & name)
SetProjectionString()
void GUIStateParams::SetProjectionString (string proj4String) inline
Definition at line 137 of file GUIStateParams.h.
References VAPoR::ParamsBase::SetValueString().
SetStatsDatasetName()
void GUIStateParams::SetStatsDatasetName (std::string & name)
Member Data Documentation
_flowDimensionalityTag
const string GUIStateParams::_flowDimensionalityTag static
Definition at line 217 of file GUIStateParams.h.
BookmarksTag
const string GUIStateParams::BookmarksTag static
Definition at line 218 of file GUIStateParams.h.
m_activeVisualizer
const string GUIStateParams::m_activeVisualizer static
Definition at line 205 of file GUIStateParams.h.
m_flowPathTag
const string GUIStateParams::m_flowPathTag static
Definition at line 211 of file GUIStateParams.h.
m_imagePathTag
const string GUIStateParams::m_imagePathTag static
Definition at line 208 of file GUIStateParams.h.
m_imageSavePathTag
const string GUIStateParams::m_imageSavePathTag static
Definition at line 209 of file GUIStateParams.h.
m_openDataSetsTag
const string GUIStateParams::m_openDataSetsTag static
Definition at line 216 of file GUIStateParams.h.
m_pathParamsTag
const string GUIStateParams::m_pathParamsTag static
Definition at line 206 of file GUIStateParams.h.
m_plotDatasetNameTag
const string GUIStateParams::m_plotDatasetNameTag static
Definition at line 214 of file GUIStateParams.h.
m_proj4StringTag
const string GUIStateParams::m_proj4StringTag static
Definition at line 215 of file GUIStateParams.h.
m_pythonPathTag
const string GUIStateParams::m_pythonPathTag static
Definition at line 210 of file GUIStateParams.h.
m_sessionFileTag
const string GUIStateParams::m_sessionFileTag static
Definition at line 207 of file GUIStateParams.h.
m_statsDatasetNameTag
const string GUIStateParams::m_statsDatasetNameTag static
Definition at line 213 of file GUIStateParams.h.
m_tfPathTag
const string GUIStateParams::m_tfPathTag static
Definition at line 212 of file GUIStateParams.h.
MovingDomainTrackCameraTag
const string GUIStateParams::MovingDomainTrackCameraTag static
Definition at line 219 of file GUIStateParams.h.
MovingDomainTrackRenderRegionsTag
const string GUIStateParams::MovingDomainTrackRenderRegionsTag static
Definition at line 220 of file GUIStateParams.h.
The documentation for this class was generated from the following file:
/Users/pearse/VAPOR/include/vapor/GUIStateParams.h