VAPOR3: Combo Class Reference
Combo Class Reference
#include <Combo.h>
Public Slots
void SetSliderLineEdit (double)
Signals
void valueChanged (double value)
void valueChanged (int value)
Public Member Functions
Combo (QLineEdit *edit, QSlider *slider, bool intType=false)
void Update (double minValid, double maxValid, double value)
void Update (double value)
QSlider * GetSlider () const
QLineEdit * GetLineEdit () const
double GetValue () const
void SetPrecision (int precision)
void SetIntType (bool)
void SetEnabled (bool)
Detailed Description
Definition at line 22 of file Combo.h.
Constructor & Destructor Documentation
Combo()
Combo::Combo (QLineEdit * edit, QSlider * slider, bool intType = false)
Member Function Documentation
GetLineEdit()
QLineEdit * Combo::GetLineEdit () const inline
Definition at line 45 of file Combo.h.
Referenced by RangeCombo::GetLineEditMax(), and RangeCombo::GetLineEditMin().
GetSlider()
QSlider * Combo::GetSlider () const inline
Definition at line 41 of file Combo.h.
Referenced by RangeCombo::GetSliderMax(), and RangeCombo::GetSliderMin().
GetValue()
double Combo::GetValue () const inline
Definition at line 49 of file Combo.h.
SetEnabled()
void Combo::SetEnabled (bool)
SetIntType()
void Combo::SetIntType (bool)
SetPrecision()
void Combo::SetPrecision (int precision)
SetSliderLineEdit
void Combo::SetSliderLineEdit (double) slot
Update() [1/2]
void Combo::Update (double minValid, double maxValid, double value)
Update() [2/2]
void Combo::Update (double value) inline
Definition at line 37 of file Combo.h.
References Update().
Referenced by Update().
valueChanged [1/2]
void Combo::valueChanged (double value) signal
valueChanged [2/2]
void Combo::valueChanged (int value) signal
The documentation for this class was generated from the following file:
/Users/pearse/VAPOR/apps/vaporgui/Combo.h