VAPOR3: AbstractWidgetGroup< This, Widget > Class Template Reference
AbstractWidgetGroup< This, Widget > Class Template Reference
Provides an interface that standardizes widget grouping classes.
#include <AbstractWidgetGroup.h>
Public Types
typedef std::initializer_list< Widget * > List
Public Member Functions
virtual This * Add (Widget *w)
Adds a widget.
This * AddM (const List &list)
Protected Attributes
std::vector< Widget * > _children
Detailed Description
template<class This, class Widget>
class AbstractWidgetGroup< This, Widget >
Provides an interface that standardizes widget grouping classes.
Author
Stas Jaroszynski
Definition at line 10 of file AbstractWidgetGroup.h.
Member Typedef Documentation
List
template<class This , class Widget > typedef std::initializer_list<Widget *> AbstractWidgetGroup< This, Widget >::List
Definition at line 15 of file AbstractWidgetGroup.h.
Member Function Documentation
Add()
template<class This , class Widget > virtual This * AbstractWidgetGroup< This, Widget >::Add (Widget * w) inline virtual
Adds a widget.
Reimplemented in VGroup, VRouter, and WidgetGroupWrapper< This, Widget, That >.
Definition at line 18 of file AbstractWidgetGroup.h.
References AbstractWidgetGroup< This, Widget >::_children.
Referenced by WidgetGroupWrapper< This, Widget, That >::Add(), and AbstractWidgetGroup< This, Widget >::AddM().
AddM()
template<class This , class Widget > This * AbstractWidgetGroup< This, Widget >::AddM (const List & list) inline
Adds multiple widgets. Has a different name for compiler reasons.
Definition at line 25 of file AbstractWidgetGroup.h.
References AbstractWidgetGroup< This, Widget >::Add().
Member Data Documentation
_children
template<class This , class Widget > std::vector<Widget *> AbstractWidgetGroup< This, Widget >::_children protected
Definition at line 12 of file AbstractWidgetGroup.h.
Referenced by AbstractWidgetGroup< This, Widget >::Add().
The documentation for this class was generated from the following file:
/Users/pearse/VAPOR/apps/vaporgui/AbstractWidgetGroup.h