VAPOR3: ControlPointList Class Reference
ControlPointList Class Reference
#include <TFOpacityWidget.h>
Classes
class LineIterator
class PointIterator
Public Member Functions
glm::vec2 & operator[] (const int i)
int Add (const glm::vec2 &v)
int Add (const glm::vec2 &v, const int i)
int Add (const glm::vec2 &v, const LineIterator &line)
void Remove (const PointIterator &point)
int Size () const
int SizeLines () const
void Resize (int n)
PointIterator BeginPoints ()
PointIterator EndPoints ()
LineIterator BeginLines ()
LineIterator EndLines ()
Public Attributes
std::vector< glm::vec2 > _points
Detailed Description
Definition at line 7 of file TFOpacityWidget.h.
Member Function Documentation
Add() [1/3]
int ControlPointList::Add (const glm::vec2 & v) inline
Definition at line 82 of file TFOpacityWidget.h.
References _points, Add(), and Size().
Referenced by Add().
Add() [2/3]
int ControlPointList::Add (const glm::vec2 & v, const int i) inline
Definition at line 90 of file TFOpacityWidget.h.
References _points, and VAssert.
Add() [3/3]
int ControlPointList::Add (const glm::vec2 & v, const LineIterator & line) inline
Definition at line 98 of file TFOpacityWidget.h.
References _points, and VAssert.
BeginLines()
LineIterator ControlPointList::BeginLines () inline
Definition at line 117 of file TFOpacityWidget.h.
BeginPoints()
PointIterator ControlPointList::BeginPoints () inline
Definition at line 115 of file TFOpacityWidget.h.
EndLines()
LineIterator ControlPointList::EndLines () inline
Definition at line 118 of file TFOpacityWidget.h.
References SizeLines().
EndPoints()
PointIterator ControlPointList::EndPoints () inline
Definition at line 116 of file TFOpacityWidget.h.
References Size().
operator[]()
glm::vec2 & ControlPointList::operator[] (const int i) inline
Definition at line 76 of file TFOpacityWidget.h.
References _points, and VAssert.
Remove()
void ControlPointList::Remove (const PointIterator & point) inline
Definition at line 105 of file TFOpacityWidget.h.
References _points, Size(), and VAssert.
Resize()
void ControlPointList::Resize (int n) inline
Definition at line 113 of file TFOpacityWidget.h.
References _points.
Size()
int ControlPointList::Size () const inline
Definition at line 111 of file TFOpacityWidget.h.
References _points.
Referenced by Add(), EndPoints(), ControlPointList::PointIterator::IsLast(), Remove(), and SizeLines().
SizeLines()
int ControlPointList::SizeLines () const inline
Definition at line 112 of file TFOpacityWidget.h.
References Size().
Referenced by EndLines().
Member Data Documentation
_points
std::vector<glm::vec2> ControlPointList::_points
Definition at line 73 of file TFOpacityWidget.h.
Referenced by Add(), operator[](), Remove(), Resize(), and Size().
The documentation for this class was generated from the following file:
/Users/pearse/VAPOR/apps/vaporgui/TFOpacityWidget.h