VAPOR3: TabManager Class Reference
TabManager Class Reference
VAPOR GUI Developer API
A class that manages the contents of the parameter tabs in VAPOR GUI.
#include <TabManager.h>
Public Slots
void UseHomeViewpoint ()
void SetHomeViewpoint ()
void ViewAll ()
void AlignView (int axis)
Signals
void ActiveEventRouterChanged (string type)
void Proj4StringChanged (string proj4String)
Proj4 string changed.
Public Member Functions
TabManager (QWidget *, VAPoR::ControlExec *ce)
void Update ()
Update from current state.
void MoveToFront (string subTabName)
vector< string > GetInstalledTabNames (bool renderOnly) const
virtual void GetWebHelp (string tabName, std::vector< std::pair< string, string > > &help) const
void EnableRouters (bool onOff)
Enable or disable widgets associated with all event routers.
void Shutdown ()
void Restart ()
void Reinit ()
void LoadDataNotify (string dataSetName)
Detailed Description
A class that manages the contents of the parameter tabs in VAPOR GUI.
Author
Alan Norton
Version
3.0
Date
May 2015
Definition at line 73 of file TabManager.h.
Constructor & Destructor Documentation
TabManager()
TabManager::TabManager (QWidget * , VAPoR::ControlExec * ce)
Member Function Documentation
ActiveEventRouterChanged
void TabManager::ActiveEventRouterChanged (string type) signal
Triggered when currently active event router changes
Parameters
[in] type Type of event router as returned by EventRouter::GetType()
AlignView
void TabManager::AlignView (int axis) inline slot
Definition at line 127 of file TabManager.h.
References NavigationUtils::AlignView().
EnableRouters()
void TabManager::EnableRouters (bool onOff)
Enable or disable widgets associated with all event routers.
GetInstalledTabNames()
vector< string > TabManager::GetInstalledTabNames (bool renderOnly) const
Get list of Installed Tab names
Parameters
[in] renderOnly If true only return render event routers. See GetRenderEventRouter()
GetWebHelp()
virtual void TabManager::GetWebHelp (string tabName, std::vector< std::pair< string, string > > & help) const virtual
LoadDataNotify()
void TabManager::LoadDataNotify (string dataSetName)
Notify TabManager that a new data set has been loaded
MoveToFront()
void TabManager::MoveToFront (string subTabName)
Make the specified EventRouter be displayed in front.
Parameters
[in] widgetTag is the Params tag that should be moved to front.
Returns
the tab position in the associated sub tab.
Proj4StringChanged
void TabManager::Proj4StringChanged (string proj4String) signal
Proj4 string changed.
Reinit()
void TabManager::Reinit ()
Restart()
void TabManager::Restart ()
SetHomeViewpoint
void TabManager::SetHomeViewpoint () inline slot
Definition at line 125 of file TabManager.h.
References NavigationUtils::SetHomeViewpoint().
Shutdown()
void TabManager::Shutdown ()
Update()
void TabManager::Update ()
Update from current state.
UseHomeViewpoint
void TabManager::UseHomeViewpoint () inline slot
Definition at line 124 of file TabManager.h.
References NavigationUtils::UseHomeViewpoint().
ViewAll
void TabManager::ViewAll () inline slot
Definition at line 126 of file TabManager.h.
References NavigationUtils::ViewAll().
The documentation for this class was generated from the following file:
/Users/pearse/VAPOR/apps/vaporgui/TabManager.h