VAPOR3: ControlPointList::PointIterator Class Reference
ControlPointList::PointIterator Class Reference
#include <TFOpacityWidget.h>
Public Member Functions
PointIterator ()
PointIterator & operator++ ()
PointIterator & operator-- ()
PointIterator operator+ (int x) const
PointIterator operator- (int x) const
glm::vec2 & operator* ()
bool operator!= (const PointIterator &other)
bool operator== (const PointIterator &other)
bool IsFirst () const
bool IsLast () const
int Index () const
Friends
class ControlPointList
Detailed Description
Definition at line 9 of file TFOpacityWidget.h.
Constructor & Destructor Documentation
PointIterator()
ControlPointList::PointIterator::PointIterator () inline
Definition at line 16 of file TFOpacityWidget.h.
Referenced by operator+(), and operator-().
Member Function Documentation
Index()
int ControlPointList::PointIterator::Index () const inline
Definition at line 35 of file TFOpacityWidget.h.
IsFirst()
bool ControlPointList::PointIterator::IsFirst () const inline
Definition at line 33 of file TFOpacityWidget.h.
IsLast()
bool ControlPointList::PointIterator::IsLast () const inline
Definition at line 34 of file TFOpacityWidget.h.
References ControlPointList::Size().
operator!=()
bool ControlPointList::PointIterator::operator!= (const PointIterator & other) inline
Definition at line 30 of file TFOpacityWidget.h.
operator*()
glm::vec2 & ControlPointList::PointIterator::operator* () inline
Definition at line 29 of file TFOpacityWidget.h.
operator+()
PointIterator ControlPointList::PointIterator::operator+ (int x) const inline
Definition at line 27 of file TFOpacityWidget.h.
References PointIterator().
operator++()
PointIterator & ControlPointList::PointIterator::operator++ () inline
Definition at line 17 of file TFOpacityWidget.h.
operator-()
PointIterator ControlPointList::PointIterator::operator- (int x) const inline
Definition at line 28 of file TFOpacityWidget.h.
References PointIterator().
operator--()
PointIterator & ControlPointList::PointIterator::operator-- () inline
Definition at line 22 of file TFOpacityWidget.h.
operator==()
bool ControlPointList::PointIterator::operator== (const PointIterator & other) inline
Definition at line 31 of file TFOpacityWidget.h.
Friends And Related Function Documentation
ControlPointList
friend class ControlPointList friend
Definition at line 37 of file TFOpacityWidget.h.
The documentation for this class was generated from the following file:
/Users/pearse/VAPOR/apps/vaporgui/TFOpacityWidget.h