VAPOR3: VAPoR::ImageParams Class Reference
VAPoR::ImageParams Class Reference
#include <ImageParams.h>
Public Member Functions
ImageParams (DataMgr *dataManager, ParamsBase::StateSave *stateSave)
ImageParams (DataMgr *dataManager, ParamsBase::StateSave *stateSave, XmlNode *xmlNode)
virtual ~ImageParams ()
virtual int Initialize () override
virtual size_t GetRenderDim () const override
void SetImagePath (std::string file)
std::string GetImagePath () const
bool GetIsGeoRef () const
void SetIsGeoRef (bool val)
bool GetIgnoreTransparency () const
void SetIgnoreTransparency (bool val)
int GetOrientation () const
void SetOrientation (int val)
int GetTMSLOD () const
void SetTMSLOD (int val)
int GetNumTMSLODs () const
virtual string GetActualColorMapVariableName () const override
Public Member Functions inherited from VAPoR::RenderParams
RenderParams (DataMgr *dataMgr, ParamsBase::StateSave *ssave, const string &classname, int maxdim=3)
RenderParams (DataMgr *dataMgr, ParamsBase::StateSave *ssave, XmlNode *node, int maxdim=3)
RenderParams (const RenderParams &rhs)
RenderParams & operator= (const RenderParams &rhs)
virtual ~RenderParams ()
virtual int Initialize ()
int ResetUserExtentsToDataExents (string var="")
virtual bool IsEnabled () const
virtual void SetEnabled (bool val)
virtual void SetVariableName (string varName)
string GetVariableName () const
virtual void SetAuxVariableNames (vector< string > varName)
vector< string > GetAuxVariableNames () const
bool UseAuxVariable () const
string GetFirstVariableName () const
virtual void SetFieldVariableNames (vector< string > varNames)
void SetXFieldVariableName (std::string varName)
void SetYFieldVariableName (std::string varName)
void SetZFieldVariableName (std::string varName)
vector< string > GetFieldVariableNames () const
std::string GetXFieldVariableName () const
std::string GetYFieldVariableName () const
std::string GetZFieldVariableName () const
vector< string > GetDistribVariableNames () const
virtual void SetRefinementLevel (int numrefinements)
virtual int GetRefinementLevel () const
virtual int GetCompressionLevel () const
virtual void SetCompressionLevel (int val)
void SetHistoStretch (float factor)
float GetHistoStretch () const
virtual ColorbarPbase * GetColorbarPbase () const
Obtain ColorbarPBase (used to specify Color Bar properties) from RenderParams.
virtual void SetColorbarPbase (ColorbarPbase *pb)
virtual MapperFunction * GetMapperFunc (string varname)
virtual void RemoveMapperFunc (string varname)
Remove the mapper function for the named variable.
virtual void SetMapperFunc (string varname, MapperFunction *tf)
virtual Box * GetBox () const
void SetCursorCoords (const float coords[2])
void GetCursorCoords (float coords[2]) const
virtual void SetHeightVariableName (string varname)
virtual string GetHeightVariableName () const
bool UseSingleColor () const
virtual void SetColorMapVariableName (string varname)
virtual string GetColorMapVariableName () const
virtual string GetActualColorMapVariableName () const =0
void SetUseSingleColor (bool val)
void SetConstantColor (const float rgb[3])
void SetConstantColor (vector< float > rgb)
void GetConstantColor (float rgb[3]) const
vector< float > GetConstantColor () const
void SetConstantOpacity (float o)
float GetConstantOpacity () const
size_t GetCurrentTimestep () const
void SetCurrentTimestep (size_t ts)
virtual Transform * GetTransform () const
Access the transform used by the renderer.
void initializeBypassFlags ()
virtual void SetDefaultVariables (int dim, bool secondaryColormapVariable)
virtual size_t GetRenderDim () const =0
virtual bool HasIsoValues () const
This should be overriden by params for renderes that support iso values to return true.
virtual vector< double > GetIsoValues (const string &variable)
virtual void SetIsoValues (const string &variable, const vector< double > &values)
vector< double > GetIsoValues ()
void SetIsoValues (const vector< double > &values)
virtual bool GetOrientable () const
Return whether a renderer can be oriented - IE, can this renderer be rotated about an origin point?
vector< double > GetSlicePlaneRotation () const
vector< double > GetSlicePlaneOrigin () const
vector< double > GetSlicePlaneNormal () const
double GetXSlicePlaneOrigin () const
double GetYSlicePlaneOrigin () const
double GetZSlicePlaneOrigin () const
void SetXSlicePlaneOrigin (double xOrigin)
void SetYSlicePlaneOrigin (double yOrigin)
void SetZSlicePlaneOrigin (double zOrigin)
void SetSlicePlaneQuad (const std::vector< CoordType > &quad)
std::vector< CoordType > GetSlicePlaneQuad () const
Public Member Functions inherited from VAPoR::ParamsBase
ParamsBase (StateSave *ssave, const string &classname)
ParamsBase (StateSave *ssave, XmlNode *node)
ParamsBase (const ParamsBase &rhs)
Copy constructor.
ParamsBase & operator= (const ParamsBase &rhs)
ParamsBase (ParamsBase &&)=delete
ParamsBase & operator= (ParamsBase &)=delete
bool operator== (const ParamsBase &rhs) const
Equivalence operator.
bool operator!= (const ParamsBase &rhs) const
virtual ~ParamsBase ()
void SetParent (ParamsBase *parent)
XmlNode * GetNode () const
void BeginGroup (const string &description)
void EndGroup ()
void IntermediateChange ()
virtual vector< long > GetValueLongVec (const string tag) const
virtual vector< long > GetValueLongVec (const string tag, const vector< long > &defaultVal) const
virtual long GetValueLong (const string tag, long defaultVal) const
virtual vector< double > GetValueDoubleVec (const string tag) const
virtual vector< double > GetValueDoubleVec (const string tag, const vector< double > &defaultVal) const
virtual double GetValueDouble (const string tag, double defaultVal) const
virtual vector< string > GetValueStringVec (const string tag) const
virtual vector< string > GetValueStringVec (const string tag, const vector< string > &defaultVal) const
virtual string GetValueString (const string tag, string defaultVal) const
virtual void SetValueLongVec (const string &tag, string description, const vector< long > &values)
virtual void SetValueLong (const string &tag, string description, long value)
virtual void SetValueDoubleVec (const string &tag, string description, const vector< double > &values)
virtual void SetValueDouble (const string &tag, string description, double value)
virtual void SetValueStringVec (const string &tag, string description, const vector< string > &values)
virtual void SetValueString (const string &tag, string description, const string &value)
string GetName () const
Public Member Functions inherited from Wasp::MyBase
MyBase ()
const string & getClassName () const
Static Public Member Functions
static std::string GetClassType ()
Static Public Member Functions inherited from Wasp::MyBase
static void SetErrMsg (const char *format,...)
Record a formatted error message.
static void SetErrMsg (int errcode, const char *format,...)
Record a formatted error message and an error code.
static const char * GetErrMsg ()
static void SetErrCode (int err_code)
Record an error code.
static int GetErrCode ()
Retrieve the current error code.
static void SetErrMsgCB (ErrMsgCB_T cb)
static ErrMsgCB_T GetErrMsgCB ()
static void SetErrMsgFilePtr (FILE *fp)
static const FILE * SetErrMsgFilePtr ()
static void SetDiagMsg (const char *format,...)
Record a formatted diagnostic message.
static const char * GetDiagMsg ()
static void SetDiagMsgCB (DiagMsgCB_T cb)
static DiagMsgCB_T GetDiagMsgCB ()
static void SetDiagMsgFilePtr (FILE *fp)
static bool EnableErrMsg (bool enable)
static bool GetEnableErrMsg ()
Static Public Attributes
static const std::string _fileNameTag
static const std::string _isGeoRefTag
static const std::string _ignoreTransparencyTag
static const std::string _opacityTag
static const std::string _TMSLODTag
static const std::string _numTMSLODTag
static const std::string _orientationTag
Static Public Attributes inherited from VAPoR::RenderParams
static const string _variableNameTag
static const string _colorMapVariableNameTag
static const string _heightVariableNameTag
static const string _useSingleColorTag
static const string _constantColorTag
static const string _CompressionLevelTag
static const string _RefinementLevelTag
static const string _xFieldVariableNameTag
static const string _yFieldVariableNameTag
static const string _zFieldVariableNameTag
static const string _constantOpacityTag
static const string CustomHistogramDataTag
static const string CustomHistogramRangeTag
static const string LightingEnabledTag
static const string UserNameTag
static const string XSlicePlaneOriginTag
static const string YSlicePlaneOriginTag
static const string ZSlicePlaneOriginTag
static const string XSlicePlaneRotationTag
static const string YSlicePlaneRotationTag
static const string ZSlicePlaneRotationTag
static const string SampleRateTag
static const string SliceOffsetTag
static const string SlicePlaneNormalXTag
static const string SlicePlaneNormalYTag
static const string SlicePlaneNormalZTag
static const string SlicePlaneOrientationModeTag
Static Public Attributes inherited from Wasp::MyBase
static char * ErrMsg
static int ErrCode
static int ErrMsgSize
static FILE * ErrMsgFilePtr
static ErrMsgCB_T ErrMsgCB
static char * DiagMsg
static int DiagMsgSize
static FILE * DiagMsgFilePtr
static DiagMsgCB_T DiagMsgCB
static bool Enabled
Additional Inherited Members
Public Types inherited from VAPoR::RenderParams
enum class SlicePlaneOrientationMode { Rotation = 0 , Normal = 1 }
Public Types inherited from Wasp::MyBase
typedef void(* ErrMsgCB_T) (const char *msg, int err_code)
typedef void(* DiagMsgCB_T) (const char *msg)
Protected Member Functions inherited from VAPoR::RenderParams
bool InitBoxFromVariable (size_t ts, string varName)
virtual bool GetUseSingleColorDefault () const
Protected Member Functions inherited from VAPoR::ParamsBase
ParamsBase (StateSave *ssave)
void Remove (const string &name)
const map< string, string > & GetAttributes ()
void Clear ()
Protected Member Functions inherited from Wasp::MyBase
void SetClassName (const string &name)
Protected Attributes inherited from VAPoR::RenderParams
DataMgr * _dataMgr
int _maxDim
Protected Attributes inherited from VAPoR::ParamsBase
StateSave * _ssave
XmlNode * _node
Detailed Description
Definition at line 10 of file ImageParams.h.
Constructor & Destructor Documentation
ImageParams() [1/2]
VAPoR::ImageParams::ImageParams (DataMgr * dataManager, ParamsBase::StateSave * stateSave)
ImageParams() [2/2]
VAPoR::ImageParams::ImageParams (DataMgr * dataManager, ParamsBase::StateSave * stateSave, XmlNode * xmlNode)
~ImageParams()
virtual VAPoR::ImageParams::~ImageParams () virtual
Member Function Documentation
GetActualColorMapVariableName()
virtual string VAPoR::ImageParams::GetActualColorMapVariableName () const inline override virtual
Due to legacy code, the "ColorMapVariableName" is not the name of the variable by which the renderer is colormapping, but rather the variable it should use if it is not already using its primary variable or a constant color. This function should return the name of the variable that is currently being used for colormapping.
Implements VAPoR::RenderParams.
Definition at line 103 of file ImageParams.h.
GetClassType()
static std::string VAPoR::ImageParams::GetClassType () inline static
Definition at line 19 of file ImageParams.h.
GetIgnoreTransparency()
bool VAPoR::ImageParams::GetIgnoreTransparency () const inline
Get whether transparency is being ignored regarding the currently selected image Valid values: 0 = transparency is being honored, 1 = transparency is being ignored
Return values
bool - State whether transparency is being ignored
Definition at line 55 of file ImageParams.h.
GetImagePath()
std::string VAPoR::ImageParams::GetImagePath () const
Set image file path
Return values
string - Path to image file
Referenced by PTMSLODInput::updateGUI().
GetIsGeoRef()
bool VAPoR::ImageParams::GetIsGeoRef () const inline
Inquire whether the currently selected image is georeferenced Valid values: 0 = do not use georeference information, 1 = use georeference information
Return values
bool - State indicating whether current image is georeferenced
Definition at line 45 of file ImageParams.h.
GetNumTMSLODs()
int VAPoR::ImageParams::GetNumTMSLODs () const inline
Get the number of available levels of detail in the currently selected file.
Return values
int The currently available levels of detail in the current file.
Definition at line 96 of file ImageParams.h.
Referenced by PTMSLODInput::updateGUI().
GetOrientation()
int VAPoR::ImageParams::GetOrientation () const inline
Definition at line 79 of file ImageParams.h.
GetRenderDim()
virtual size_t VAPoR::ImageParams::GetRenderDim () const inline override virtual
Return the renderer's current dimension
For renderers that are only capable of operating on variables of a fixed dimensionality (e.g. 2D or 3D) this function will return a constant value: the number of dimensions. For renderers that can operate on a variable of varying dimension this method returns the current dimensionality. The returned value will be between 0 and 3. A value of zero will be returned if the current dimensionality cannot be determined.
Implements VAPoR::RenderParams.
Definition at line 23 of file ImageParams.h.
GetTMSLOD()
int VAPoR::ImageParams::GetTMSLOD () const inline
Get the TMS level of detail
Return values
int Currently selected TMS level of detail. Value of -1 means we are computing a default value.
Definition at line 84 of file ImageParams.h.
Referenced by PTMSLODInput::updateGUI().
Initialize()
virtual int VAPoR::ImageParams::Initialize () override virtual
Initialize the class.
Must be called immediately after the constructor:
RenderParams(DataMgr *, ParamsBase::StateSave *, const string &, int maxdim);
The results of calling any other methods before calling Initialize() are undefined.
Subsequent calls to Initialize() after the first call are a no-op.
Return values
returns integer >= 0 on success, otherwise failure
Reimplemented from VAPoR::RenderParams.
SetIgnoreTransparency()
void VAPoR::ImageParams::SetIgnoreTransparency (bool val) inline
Set whether transparency is being ignored regarding the currently selected image Valid values: 0 = transparency is being honored, 1 = transparency is being ignored
Parameters
[in] bool - State whether transparency is being ignored
Definition at line 60 of file ImageParams.h.
SetImagePath()
void VAPoR::ImageParams::SetImagePath (std::string file) inline
Set file path for the image to be read and displayed.
Parameters
[in] string - Path to image file
Definition at line 27 of file ImageParams.h.
References Wasp::TMSUtils::GetNumTMSLODs(), and Wasp::TMSUtils::IsTMSFile().
SetIsGeoRef()
void VAPoR::ImageParams::SetIsGeoRef (bool val) inline
If the raster image contained in the path returned by GetImagePath() has georeference information (e.g. the file is a GeoTIFF) this boolean determines whether or not the georeference information is honored Valid values: 0 = do not use georeference information, 1 = use georeference information
Parameters
[in] bool - State indicating whether current image is georeferenced
Definition at line 50 of file ImageParams.h.
SetOrientation()
void VAPoR::ImageParams::SetOrientation (int val) inline
Definition at line 80 of file ImageParams.h.
SetTMSLOD()
void VAPoR::ImageParams::SetTMSLOD (int val) inline
Set the current TMS level of detail
Parameters
[in] val int val, the TMS level of detail to be applied. Value of 0 means we are computing a default value.
Definition at line 92 of file ImageParams.h.
Member Data Documentation
_fileNameTag
const std::string VAPoR::ImageParams::_fileNameTag static
Definition at line 106 of file ImageParams.h.
_ignoreTransparencyTag
const std::string VAPoR::ImageParams::_ignoreTransparencyTag static
Definition at line 108 of file ImageParams.h.
_isGeoRefTag
const std::string VAPoR::ImageParams::_isGeoRefTag static
Definition at line 107 of file ImageParams.h.
_numTMSLODTag
const std::string VAPoR::ImageParams::_numTMSLODTag static
Definition at line 111 of file ImageParams.h.
_opacityTag
const std::string VAPoR::ImageParams::_opacityTag static
Definition at line 109 of file ImageParams.h.
_orientationTag
const std::string VAPoR::ImageParams::_orientationTag static
Definition at line 112 of file ImageParams.h.
_TMSLODTag
const std::string VAPoR::ImageParams::_TMSLODTag static
Definition at line 110 of file ImageParams.h.
The documentation for this class was generated from the following file:
/Users/pearse/VAPOR/include/vapor/ImageParams.h