VAPOR3: Wasp::TMSUtils Namespace Reference
Wasp::TMSUtils Namespace Reference
Functions
COMMON_API bool IsTMSFile (std::string path)
COMMON_API std::string TilePath (std::string file, size_t tileX, size_t tileY, int lod)
COMMON_API int GetNumTMSLODs (std::string file)
Function Documentation
GetNumTMSLODs()
COMMON_API int Wasp::TMSUtils::GetNumTMSLODs (std::string file)
Referenced by VAPoR::ImageParams::SetImagePath().
IsTMSFile()
COMMON_API bool Wasp::TMSUtils::IsTMSFile (std::string path)
Referenced by VAPoR::ImageParams::SetImagePath(), and PTMSLODInput::updateGUI().
TilePath()
COMMON_API std::string Wasp::TMSUtils::TilePath (std::string file, size_t tileX, size_t tileY, int lod)