VAPOR3: ContourEventRouter Class Reference
ContourEventRouter Class Reference
VAPOR GUI Developer API
Contour renderer GUI.
#include <ContourEventRouter.h>
Public Member Functions
ContourEventRouter (QWidget *parent, VAPoR::ControlExec *ce)
bool Supports2DVariables () const
bool Supports3DVariables () const
string GetType () const
Public Member Functions inherited from RenderEventRouterGUI
RenderEventRouterGUI (VAPoR::ControlExec *ce, string paramsType)
QWidget * AddSubtab (string title, UWidget *subtab)
QWidget * AddVariablesSubtab (UWidget *subtab)
QWidget * AddAppearanceSubtab (UWidget *subtab)
QWidget * AddGeometrySubtab (UWidget *subtab)
QWidget * AddAnnotationSubtab (UWidget *subtab)
Public Member Functions inherited from RenderEventRouter
RenderEventRouter (VAPoR::ControlExec *ce, string paramsType)
virtual ~RenderEventRouter ()
void SetActive (string instName)
virtual void hookUpTab ()
virtual void updateTab ()
virtual void confirmText ()
virtual bool Supports2DVariables () const =0
virtual bool Supports3DVariables () const =0
virtual bool SupportsParticleVariables () const
void updateRenderer (VAPoR::RenderParams *rParams, bool prevEnabled, string VizName, string renderInstName, bool newWindow)
virtual void sessionLoadTF (string name)
virtual void fitToView ()
virtual ColorbarWidget * getColorbarWidget ()
virtual void variableChanged ()
VAPoR::RenderParams * GetActiveParams () const
VAPoR::DataMgr * GetActiveDataMgr () const
string GetDescription () const
string GetSmallIconImagePath () const
string GetIconImagePath () const
Public Member Functions inherited from EventRouter
EventRouter (VAPoR::ControlExec *ce, string paramsType)
virtual ~EventRouter ()
virtual VAPoR::ParamsBase * GetActiveParams () const
virtual void hookUpTab ()
virtual void GetWebHelp (std::vector< std::pair< string, string > > &help) const
virtual void updateTab ()
virtual void confirmText ()
void SetTextChanged (bool on)
virtual void captureMouseUp ()
virtual void captureMouseDown (int mouseNum)
virtual void StartCursorMove ()
virtual void EndCursorMove ()
GUIStateParams * GetStateParams () const
AnimationParams * GetAnimationParams () const
size_t GetCurrentTimeStep () const
virtual string GetType () const =0
virtual void LoadDataNotify (string dataSetName)
Static Public Member Functions
static string GetClassType ()
Static Public Member Functions inherited from EventRouter
static size_t GetCurrentTimeStep (VAPoR::ControlExec *ce)
Protected Member Functions
virtual void _updateTab ()
virtual string _getDescription () const
string _getSmallIconImagePath () const
string _getIconImagePath () const
virtual void _updateTab () override
Protected Member Functions inherited from RenderEventRouter
RenderEventRouter ()
virtual void _updateTab ()=0
virtual void _confirmText ()
virtual string _getDescription () const =0
virtual string _getSmallIconImagePath () const =0
virtual string _getIconImagePath () const =0
Protected Member Functions inherited from EventRouter
EventRouter ()
virtual void _initializeTab ()
virtual void _updateTab ()=0
virtual void _confirmText ()
Additional Inherited Members
Static Public Attributes inherited from RenderEventRouterGUI
static const std::string VariablesTabName
static const std::string AppearanceTabName
static const std::string GeometryTabName
static const std::string AnnotationTabName
Protected Attributes inherited from EventRouter
VAPoR::ControlExec * _controlExec
bool _textChangedFlag
string _paramsType
Detailed Description
Contour renderer GUI.
Author
Stas Jaroszynski
Definition at line 13 of file ContourEventRouter.h.
Constructor & Destructor Documentation
ContourEventRouter()
ContourEventRouter::ContourEventRouter (QWidget * parent, VAPoR::ControlExec * ce)
Member Function Documentation
_getDescription()
virtual string ContourEventRouter::_getDescription () const protected virtual
Implements RenderEventRouter.
_getIconImagePath()
string ContourEventRouter::_getIconImagePath () const inline protected virtual
Implements RenderEventRouter.
Definition at line 25 of file ContourEventRouter.h.
_getSmallIconImagePath()
string ContourEventRouter::_getSmallIconImagePath () const inline protected virtual
Implements RenderEventRouter.
Definition at line 24 of file ContourEventRouter.h.
_updateTab()
virtual void ContourEventRouter::_updateTab () protected virtual
Pure virtual method to set the values of all the gui elements in the tab based on current Params state. This is invoked whenever the tab is redisplayed and the values in the tab need to be refreshed. If there is a VariablesWidget, _updateTab() must invoke VariablesWidget::updateTab().
Parameters
[in] p Params instance associated with the current active tab.
Reimplemented from RenderEventRouterGUI.
GetClassType()
static string ContourEventRouter::GetClassType () inline static
Definition at line 18 of file ContourEventRouter.h.
References VAPoR::ContourRenderer::GetClassType().
Referenced by GetType().
GetType()
string ContourEventRouter::GetType () const inline virtual
Return derived class type
Return a string identifier for the derived EventRouter type
Implements EventRouter.
Definition at line 19 of file ContourEventRouter.h.
References GetClassType().
Supports2DVariables()
bool ContourEventRouter::Supports2DVariables () const inline virtual
Pure virtual method that indicates whether the current RenderEventRouter and its associated renderer support 2D variables.
Implements RenderEventRouter.
Definition at line 16 of file ContourEventRouter.h.
Supports3DVariables()
bool ContourEventRouter::Supports3DVariables () const inline virtual
Pure virtual method that indicates whether the current RenderEventRouter and its associated renderer support 3D variables.
Implements RenderEventRouter.
Definition at line 17 of file ContourEventRouter.h.
The documentation for this class was generated from the following file:
/Users/pearse/VAPOR/apps/vaporgui/ContourEventRouter.h